// Code generated by go-swagger; DO NOT EDIT.

package message

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// AttachmentParamsReader is a Reader for the AttachmentParams structure.
type AttachmentParamsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AttachmentParamsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewAttachmentParamsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewAttachmentParamsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewAttachmentParamsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/v1/message/{ID}/part/{PartID}] AttachmentParams", response, response.Code())
	}
}

// NewAttachmentParamsOK creates a AttachmentParamsOK with default headers values
func NewAttachmentParamsOK() *AttachmentParamsOK {
	return &AttachmentParamsOK{}
}

/*
AttachmentParamsOK describes a response with status code 200, with default header values.

Binary data response which inherits the attachment's content type.
*/
type AttachmentParamsOK struct {
	Payload string
}

// IsSuccess returns true when this attachment params o k response has a 2xx status code
func (o *AttachmentParamsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this attachment params o k response has a 3xx status code
func (o *AttachmentParamsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this attachment params o k response has a 4xx status code
func (o *AttachmentParamsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this attachment params o k response has a 5xx status code
func (o *AttachmentParamsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this attachment params o k response a status code equal to that given
func (o *AttachmentParamsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the attachment params o k response
func (o *AttachmentParamsOK) Code() int {
	return 200
}

func (o *AttachmentParamsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/message/{ID}/part/{PartID}][%d] attachmentParamsOK %s", 200, payload)
}

func (o *AttachmentParamsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/message/{ID}/part/{PartID}][%d] attachmentParamsOK %s", 200, payload)
}

func (o *AttachmentParamsOK) GetPayload() string {
	return o.Payload
}

func (o *AttachmentParamsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewAttachmentParamsBadRequest creates a AttachmentParamsBadRequest with default headers values
func NewAttachmentParamsBadRequest() *AttachmentParamsBadRequest {
	return &AttachmentParamsBadRequest{}
}

/*
	AttachmentParamsBadRequest describes a response with status code 400, with default header values.

	Server error will return with a 400 status code

with the error message in the body
*/
type AttachmentParamsBadRequest struct {
	Payload string
}

// IsSuccess returns true when this attachment params bad request response has a 2xx status code
func (o *AttachmentParamsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this attachment params bad request response has a 3xx status code
func (o *AttachmentParamsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this attachment params bad request response has a 4xx status code
func (o *AttachmentParamsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this attachment params bad request response has a 5xx status code
func (o *AttachmentParamsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this attachment params bad request response a status code equal to that given
func (o *AttachmentParamsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the attachment params bad request response
func (o *AttachmentParamsBadRequest) Code() int {
	return 400
}

func (o *AttachmentParamsBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/message/{ID}/part/{PartID}][%d] attachmentParamsBadRequest %s", 400, payload)
}

func (o *AttachmentParamsBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/message/{ID}/part/{PartID}][%d] attachmentParamsBadRequest %s", 400, payload)
}

func (o *AttachmentParamsBadRequest) GetPayload() string {
	return o.Payload
}

func (o *AttachmentParamsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewAttachmentParamsNotFound creates a AttachmentParamsNotFound with default headers values
func NewAttachmentParamsNotFound() *AttachmentParamsNotFound {
	return &AttachmentParamsNotFound{}
}

/*
AttachmentParamsNotFound describes a response with status code 404, with default header values.

Not found error will return a 404 status code
*/
type AttachmentParamsNotFound struct {
	Payload string
}

// IsSuccess returns true when this attachment params not found response has a 2xx status code
func (o *AttachmentParamsNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this attachment params not found response has a 3xx status code
func (o *AttachmentParamsNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this attachment params not found response has a 4xx status code
func (o *AttachmentParamsNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this attachment params not found response has a 5xx status code
func (o *AttachmentParamsNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this attachment params not found response a status code equal to that given
func (o *AttachmentParamsNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the attachment params not found response
func (o *AttachmentParamsNotFound) Code() int {
	return 404
}

func (o *AttachmentParamsNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/message/{ID}/part/{PartID}][%d] attachmentParamsNotFound %s", 404, payload)
}

func (o *AttachmentParamsNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/message/{ID}/part/{PartID}][%d] attachmentParamsNotFound %s", 404, payload)
}

func (o *AttachmentParamsNotFound) GetPayload() string {
	return o.Payload
}

func (o *AttachmentParamsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
