// Code generated by go-swagger; DO NOT EDIT.

package message

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewAttachmentParamsParams creates a new AttachmentParamsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAttachmentParamsParams() *AttachmentParamsParams {
	return &AttachmentParamsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAttachmentParamsParamsWithTimeout creates a new AttachmentParamsParams object
// with the ability to set a timeout on a request.
func NewAttachmentParamsParamsWithTimeout(timeout time.Duration) *AttachmentParamsParams {
	return &AttachmentParamsParams{
		timeout: timeout,
	}
}

// NewAttachmentParamsParamsWithContext creates a new AttachmentParamsParams object
// with the ability to set a context for a request.
func NewAttachmentParamsParamsWithContext(ctx context.Context) *AttachmentParamsParams {
	return &AttachmentParamsParams{
		Context: ctx,
	}
}

// NewAttachmentParamsParamsWithHTTPClient creates a new AttachmentParamsParams object
// with the ability to set a custom HTTPClient for a request.
func NewAttachmentParamsParamsWithHTTPClient(client *http.Client) *AttachmentParamsParams {
	return &AttachmentParamsParams{
		HTTPClient: client,
	}
}

/*
AttachmentParamsParams contains all the parameters to send to the API endpoint

	for the attachment params operation.

	Typically these are written to a http.Request.
*/
type AttachmentParamsParams struct {

	/* ID.

	   Message database ID or "latest"
	*/
	ID string

	/* PartID.

	   Attachment part ID
	*/
	PartID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the attachment params params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AttachmentParamsParams) WithDefaults() *AttachmentParamsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the attachment params params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AttachmentParamsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the attachment params params
func (o *AttachmentParamsParams) WithTimeout(timeout time.Duration) *AttachmentParamsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the attachment params params
func (o *AttachmentParamsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the attachment params params
func (o *AttachmentParamsParams) WithContext(ctx context.Context) *AttachmentParamsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the attachment params params
func (o *AttachmentParamsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the attachment params params
func (o *AttachmentParamsParams) WithHTTPClient(client *http.Client) *AttachmentParamsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the attachment params params
func (o *AttachmentParamsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the attachment params params
func (o *AttachmentParamsParams) WithID(id string) *AttachmentParamsParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the attachment params params
func (o *AttachmentParamsParams) SetID(id string) {
	o.ID = id
}

// WithPartID adds the partID to the attachment params params
func (o *AttachmentParamsParams) WithPartID(partID string) *AttachmentParamsParams {
	o.SetPartID(partID)
	return o
}

// SetPartID adds the partId to the attachment params params
func (o *AttachmentParamsParams) SetPartID(partID string) {
	o.PartID = partID
}

// WriteToRequest writes these params to a swagger request
func (o *AttachmentParamsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param ID
	if err := r.SetPathParam("ID", o.ID); err != nil {
		return err
	}

	// path param PartID
	if err := r.SetPathParam("PartID", o.PartID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
