// Code generated by go-swagger; DO NOT EDIT.

package message

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DownloadRawParamsReader is a Reader for the DownloadRawParams structure.
type DownloadRawParamsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DownloadRawParamsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewDownloadRawParamsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDownloadRawParamsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDownloadRawParamsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/v1/message/{ID}/raw] DownloadRawParams", response, response.Code())
	}
}

// NewDownloadRawParamsOK creates a DownloadRawParamsOK with default headers values
func NewDownloadRawParamsOK() *DownloadRawParamsOK {
	return &DownloadRawParamsOK{}
}

/*
DownloadRawParamsOK describes a response with status code 200, with default header values.

Plain text response
*/
type DownloadRawParamsOK struct {
	Payload string
}

// IsSuccess returns true when this download raw params o k response has a 2xx status code
func (o *DownloadRawParamsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this download raw params o k response has a 3xx status code
func (o *DownloadRawParamsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this download raw params o k response has a 4xx status code
func (o *DownloadRawParamsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this download raw params o k response has a 5xx status code
func (o *DownloadRawParamsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this download raw params o k response a status code equal to that given
func (o *DownloadRawParamsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the download raw params o k response
func (o *DownloadRawParamsOK) Code() int {
	return 200
}

func (o *DownloadRawParamsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/message/{ID}/raw][%d] downloadRawParamsOK %s", 200, payload)
}

func (o *DownloadRawParamsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/message/{ID}/raw][%d] downloadRawParamsOK %s", 200, payload)
}

func (o *DownloadRawParamsOK) GetPayload() string {
	return o.Payload
}

func (o *DownloadRawParamsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDownloadRawParamsBadRequest creates a DownloadRawParamsBadRequest with default headers values
func NewDownloadRawParamsBadRequest() *DownloadRawParamsBadRequest {
	return &DownloadRawParamsBadRequest{}
}

/*
	DownloadRawParamsBadRequest describes a response with status code 400, with default header values.

	Server error will return with a 400 status code

with the error message in the body
*/
type DownloadRawParamsBadRequest struct {
	Payload string
}

// IsSuccess returns true when this download raw params bad request response has a 2xx status code
func (o *DownloadRawParamsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this download raw params bad request response has a 3xx status code
func (o *DownloadRawParamsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this download raw params bad request response has a 4xx status code
func (o *DownloadRawParamsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this download raw params bad request response has a 5xx status code
func (o *DownloadRawParamsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this download raw params bad request response a status code equal to that given
func (o *DownloadRawParamsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the download raw params bad request response
func (o *DownloadRawParamsBadRequest) Code() int {
	return 400
}

func (o *DownloadRawParamsBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/message/{ID}/raw][%d] downloadRawParamsBadRequest %s", 400, payload)
}

func (o *DownloadRawParamsBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/message/{ID}/raw][%d] downloadRawParamsBadRequest %s", 400, payload)
}

func (o *DownloadRawParamsBadRequest) GetPayload() string {
	return o.Payload
}

func (o *DownloadRawParamsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDownloadRawParamsNotFound creates a DownloadRawParamsNotFound with default headers values
func NewDownloadRawParamsNotFound() *DownloadRawParamsNotFound {
	return &DownloadRawParamsNotFound{}
}

/*
DownloadRawParamsNotFound describes a response with status code 404, with default header values.

Not found error will return a 404 status code
*/
type DownloadRawParamsNotFound struct {
	Payload string
}

// IsSuccess returns true when this download raw params not found response has a 2xx status code
func (o *DownloadRawParamsNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this download raw params not found response has a 3xx status code
func (o *DownloadRawParamsNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this download raw params not found response has a 4xx status code
func (o *DownloadRawParamsNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this download raw params not found response has a 5xx status code
func (o *DownloadRawParamsNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this download raw params not found response a status code equal to that given
func (o *DownloadRawParamsNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the download raw params not found response
func (o *DownloadRawParamsNotFound) Code() int {
	return 404
}

func (o *DownloadRawParamsNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/message/{ID}/raw][%d] downloadRawParamsNotFound %s", 404, payload)
}

func (o *DownloadRawParamsNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/message/{ID}/raw][%d] downloadRawParamsNotFound %s", 404, payload)
}

func (o *DownloadRawParamsNotFound) GetPayload() string {
	return o.Payload
}

func (o *DownloadRawParamsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
