// Code generated by go-swagger; DO NOT EDIT.

package message

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetHeadersParamsParams creates a new GetHeadersParamsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetHeadersParamsParams() *GetHeadersParamsParams {
	return &GetHeadersParamsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetHeadersParamsParamsWithTimeout creates a new GetHeadersParamsParams object
// with the ability to set a timeout on a request.
func NewGetHeadersParamsParamsWithTimeout(timeout time.Duration) *GetHeadersParamsParams {
	return &GetHeadersParamsParams{
		timeout: timeout,
	}
}

// NewGetHeadersParamsParamsWithContext creates a new GetHeadersParamsParams object
// with the ability to set a context for a request.
func NewGetHeadersParamsParamsWithContext(ctx context.Context) *GetHeadersParamsParams {
	return &GetHeadersParamsParams{
		Context: ctx,
	}
}

// NewGetHeadersParamsParamsWithHTTPClient creates a new GetHeadersParamsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetHeadersParamsParamsWithHTTPClient(client *http.Client) *GetHeadersParamsParams {
	return &GetHeadersParamsParams{
		HTTPClient: client,
	}
}

/*
GetHeadersParamsParams contains all the parameters to send to the API endpoint

	for the get headers params operation.

	Typically these are written to a http.Request.
*/
type GetHeadersParamsParams struct {

	/* ID.

	   Message database ID or "latest"
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get headers params params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetHeadersParamsParams) WithDefaults() *GetHeadersParamsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get headers params params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetHeadersParamsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get headers params params
func (o *GetHeadersParamsParams) WithTimeout(timeout time.Duration) *GetHeadersParamsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get headers params params
func (o *GetHeadersParamsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get headers params params
func (o *GetHeadersParamsParams) WithContext(ctx context.Context) *GetHeadersParamsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get headers params params
func (o *GetHeadersParamsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get headers params params
func (o *GetHeadersParamsParams) WithHTTPClient(client *http.Client) *GetHeadersParamsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get headers params params
func (o *GetHeadersParamsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get headers params params
func (o *GetHeadersParamsParams) WithID(id string) *GetHeadersParamsParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get headers params params
func (o *GetHeadersParamsParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetHeadersParamsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param ID
	if err := r.SetPathParam("ID", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
