// Code generated by go-swagger; DO NOT EDIT.

package message

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/otakakot/sample-mailpit/pkg/mailpit/models"
)

// GetMessageParamsReader is a Reader for the GetMessageParams structure.
type GetMessageParamsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetMessageParamsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetMessageParamsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetMessageParamsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetMessageParamsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/v1/message/{ID}] GetMessageParams", response, response.Code())
	}
}

// NewGetMessageParamsOK creates a GetMessageParamsOK with default headers values
func NewGetMessageParamsOK() *GetMessageParamsOK {
	return &GetMessageParamsOK{}
}

/*
GetMessageParamsOK describes a response with status code 200, with default header values.

Message
*/
type GetMessageParamsOK struct {
	Payload *models.Message
}

// IsSuccess returns true when this get message params o k response has a 2xx status code
func (o *GetMessageParamsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get message params o k response has a 3xx status code
func (o *GetMessageParamsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get message params o k response has a 4xx status code
func (o *GetMessageParamsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get message params o k response has a 5xx status code
func (o *GetMessageParamsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get message params o k response a status code equal to that given
func (o *GetMessageParamsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get message params o k response
func (o *GetMessageParamsOK) Code() int {
	return 200
}

func (o *GetMessageParamsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/message/{ID}][%d] getMessageParamsOK %s", 200, payload)
}

func (o *GetMessageParamsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/message/{ID}][%d] getMessageParamsOK %s", 200, payload)
}

func (o *GetMessageParamsOK) GetPayload() *models.Message {
	return o.Payload
}

func (o *GetMessageParamsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Message)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetMessageParamsBadRequest creates a GetMessageParamsBadRequest with default headers values
func NewGetMessageParamsBadRequest() *GetMessageParamsBadRequest {
	return &GetMessageParamsBadRequest{}
}

/*
	GetMessageParamsBadRequest describes a response with status code 400, with default header values.

	Server error will return with a 400 status code

with the error message in the body
*/
type GetMessageParamsBadRequest struct {
	Payload string
}

// IsSuccess returns true when this get message params bad request response has a 2xx status code
func (o *GetMessageParamsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get message params bad request response has a 3xx status code
func (o *GetMessageParamsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get message params bad request response has a 4xx status code
func (o *GetMessageParamsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get message params bad request response has a 5xx status code
func (o *GetMessageParamsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get message params bad request response a status code equal to that given
func (o *GetMessageParamsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get message params bad request response
func (o *GetMessageParamsBadRequest) Code() int {
	return 400
}

func (o *GetMessageParamsBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/message/{ID}][%d] getMessageParamsBadRequest %s", 400, payload)
}

func (o *GetMessageParamsBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/message/{ID}][%d] getMessageParamsBadRequest %s", 400, payload)
}

func (o *GetMessageParamsBadRequest) GetPayload() string {
	return o.Payload
}

func (o *GetMessageParamsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetMessageParamsNotFound creates a GetMessageParamsNotFound with default headers values
func NewGetMessageParamsNotFound() *GetMessageParamsNotFound {
	return &GetMessageParamsNotFound{}
}

/*
GetMessageParamsNotFound describes a response with status code 404, with default header values.

Not found error will return a 404 status code
*/
type GetMessageParamsNotFound struct {
	Payload string
}

// IsSuccess returns true when this get message params not found response has a 2xx status code
func (o *GetMessageParamsNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get message params not found response has a 3xx status code
func (o *GetMessageParamsNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get message params not found response has a 4xx status code
func (o *GetMessageParamsNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get message params not found response has a 5xx status code
func (o *GetMessageParamsNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get message params not found response a status code equal to that given
func (o *GetMessageParamsNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get message params not found response
func (o *GetMessageParamsNotFound) Code() int {
	return 404
}

func (o *GetMessageParamsNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/message/{ID}][%d] getMessageParamsNotFound %s", 404, payload)
}

func (o *GetMessageParamsNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/message/{ID}][%d] getMessageParamsNotFound %s", 404, payload)
}

func (o *GetMessageParamsNotFound) GetPayload() string {
	return o.Payload
}

func (o *GetMessageParamsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
