// Code generated by go-swagger; DO NOT EDIT.

package message

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/otakakot/sample-mailpit/pkg/mailpit/models"
)

// GetHeadersParamsReader is a Reader for the GetHeadersParams structure.
type GetHeadersParamsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetHeadersParamsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetHeadersParamsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetHeadersParamsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetHeadersParamsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/v1/message/{ID}/headers] GetHeadersParams", response, response.Code())
	}
}

// NewGetHeadersParamsOK creates a GetHeadersParamsOK with default headers values
func NewGetHeadersParamsOK() *GetHeadersParamsOK {
	return &GetHeadersParamsOK{}
}

/*
GetHeadersParamsOK describes a response with status code 200, with default header values.

MessageHeadersResponse
*/
type GetHeadersParamsOK struct {
	Payload models.MessageHeadersResponse
}

// IsSuccess returns true when this get headers params o k response has a 2xx status code
func (o *GetHeadersParamsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get headers params o k response has a 3xx status code
func (o *GetHeadersParamsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get headers params o k response has a 4xx status code
func (o *GetHeadersParamsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get headers params o k response has a 5xx status code
func (o *GetHeadersParamsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get headers params o k response a status code equal to that given
func (o *GetHeadersParamsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get headers params o k response
func (o *GetHeadersParamsOK) Code() int {
	return 200
}

func (o *GetHeadersParamsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/message/{ID}/headers][%d] getHeadersParamsOK %s", 200, payload)
}

func (o *GetHeadersParamsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/message/{ID}/headers][%d] getHeadersParamsOK %s", 200, payload)
}

func (o *GetHeadersParamsOK) GetPayload() models.MessageHeadersResponse {
	return o.Payload
}

func (o *GetHeadersParamsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetHeadersParamsBadRequest creates a GetHeadersParamsBadRequest with default headers values
func NewGetHeadersParamsBadRequest() *GetHeadersParamsBadRequest {
	return &GetHeadersParamsBadRequest{}
}

/*
	GetHeadersParamsBadRequest describes a response with status code 400, with default header values.

	Server error will return with a 400 status code

with the error message in the body
*/
type GetHeadersParamsBadRequest struct {
	Payload string
}

// IsSuccess returns true when this get headers params bad request response has a 2xx status code
func (o *GetHeadersParamsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get headers params bad request response has a 3xx status code
func (o *GetHeadersParamsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get headers params bad request response has a 4xx status code
func (o *GetHeadersParamsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get headers params bad request response has a 5xx status code
func (o *GetHeadersParamsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get headers params bad request response a status code equal to that given
func (o *GetHeadersParamsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get headers params bad request response
func (o *GetHeadersParamsBadRequest) Code() int {
	return 400
}

func (o *GetHeadersParamsBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/message/{ID}/headers][%d] getHeadersParamsBadRequest %s", 400, payload)
}

func (o *GetHeadersParamsBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/message/{ID}/headers][%d] getHeadersParamsBadRequest %s", 400, payload)
}

func (o *GetHeadersParamsBadRequest) GetPayload() string {
	return o.Payload
}

func (o *GetHeadersParamsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetHeadersParamsNotFound creates a GetHeadersParamsNotFound with default headers values
func NewGetHeadersParamsNotFound() *GetHeadersParamsNotFound {
	return &GetHeadersParamsNotFound{}
}

/*
GetHeadersParamsNotFound describes a response with status code 404, with default header values.

Not found error will return a 404 status code
*/
type GetHeadersParamsNotFound struct {
	Payload string
}

// IsSuccess returns true when this get headers params not found response has a 2xx status code
func (o *GetHeadersParamsNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get headers params not found response has a 3xx status code
func (o *GetHeadersParamsNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get headers params not found response has a 4xx status code
func (o *GetHeadersParamsNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get headers params not found response has a 5xx status code
func (o *GetHeadersParamsNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get headers params not found response a status code equal to that given
func (o *GetHeadersParamsNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get headers params not found response
func (o *GetHeadersParamsNotFound) Code() int {
	return 404
}

func (o *GetHeadersParamsNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/message/{ID}/headers][%d] getHeadersParamsNotFound %s", 404, payload)
}

func (o *GetHeadersParamsNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/message/{ID}/headers][%d] getHeadersParamsNotFound %s", 404, payload)
}

func (o *GetHeadersParamsNotFound) GetPayload() string {
	return o.Payload
}

func (o *GetHeadersParamsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
