// Code generated by go-swagger; DO NOT EDIT.

package message

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetMessageParamsParams creates a new GetMessageParamsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetMessageParamsParams() *GetMessageParamsParams {
	return &GetMessageParamsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetMessageParamsParamsWithTimeout creates a new GetMessageParamsParams object
// with the ability to set a timeout on a request.
func NewGetMessageParamsParamsWithTimeout(timeout time.Duration) *GetMessageParamsParams {
	return &GetMessageParamsParams{
		timeout: timeout,
	}
}

// NewGetMessageParamsParamsWithContext creates a new GetMessageParamsParams object
// with the ability to set a context for a request.
func NewGetMessageParamsParamsWithContext(ctx context.Context) *GetMessageParamsParams {
	return &GetMessageParamsParams{
		Context: ctx,
	}
}

// NewGetMessageParamsParamsWithHTTPClient creates a new GetMessageParamsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetMessageParamsParamsWithHTTPClient(client *http.Client) *GetMessageParamsParams {
	return &GetMessageParamsParams{
		HTTPClient: client,
	}
}

/*
GetMessageParamsParams contains all the parameters to send to the API endpoint

	for the get message params operation.

	Typically these are written to a http.Request.
*/
type GetMessageParamsParams struct {

	/* ID.

	   Message database ID or "latest"
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get message params params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetMessageParamsParams) WithDefaults() *GetMessageParamsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get message params params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetMessageParamsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get message params params
func (o *GetMessageParamsParams) WithTimeout(timeout time.Duration) *GetMessageParamsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get message params params
func (o *GetMessageParamsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get message params params
func (o *GetMessageParamsParams) WithContext(ctx context.Context) *GetMessageParamsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get message params params
func (o *GetMessageParamsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get message params params
func (o *GetMessageParamsParams) WithHTTPClient(client *http.Client) *GetMessageParamsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get message params params
func (o *GetMessageParamsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get message params params
func (o *GetMessageParamsParams) WithID(id string) *GetMessageParamsParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get message params params
func (o *GetMessageParamsParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetMessageParamsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param ID
	if err := r.SetPathParam("ID", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
