// Code generated by go-swagger; DO NOT EDIT.

package message

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new message API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new message API client with basic auth credentials.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new message API client with a bearer token for authentication.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

/*
Client for message API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// This client is generated with a few options you might find useful for your swagger spec.
//
// Feel free to add you own set of options.

// WithAccept allows the client to force the Accept header
// to negotiate a specific Producer from the server.
//
// You may use this option to set arbitrary extensions to your MIME media type.
func WithAccept(mime string) ClientOption {
	return func(r *runtime.ClientOperation) {
		r.ProducesMediaTypes = []string{mime}
	}
}

// WithAcceptApplicationStar sets the Accept header to "application/*".
func WithAcceptApplicationStar(r *runtime.ClientOperation) {
	r.ProducesMediaTypes = []string{"application/*"}
}

// WithAcceptApplicationJSON sets the Accept header to "application/json".
func WithAcceptApplicationJSON(r *runtime.ClientOperation) {
	r.ProducesMediaTypes = []string{"application/json"}
}

// WithAcceptImageStar sets the Accept header to "image/*".
func WithAcceptImageStar(r *runtime.ClientOperation) {
	r.ProducesMediaTypes = []string{"image/*"}
}

// WithAcceptImageJpeg sets the Accept header to "image/jpeg".
func WithAcceptImageJpeg(r *runtime.ClientOperation) {
	r.ProducesMediaTypes = []string{"image/jpeg"}
}

// WithAcceptTextStar sets the Accept header to "text/*".
func WithAcceptTextStar(r *runtime.ClientOperation) {
	r.ProducesMediaTypes = []string{"text/*"}
}

// WithAcceptTextPlain sets the Accept header to "text/plain".
func WithAcceptTextPlain(r *runtime.ClientOperation) {
	r.ProducesMediaTypes = []string{"text/plain"}
}

// ClientService is the interface for Client methods
type ClientService interface {
	AttachmentParams(params *AttachmentParamsParams, opts ...ClientOption) (*AttachmentParamsOK, error)

	DownloadRawParams(params *DownloadRawParamsParams, opts ...ClientOption) (*DownloadRawParamsOK, error)

	GetHeadersParams(params *GetHeadersParamsParams, opts ...ClientOption) (*GetHeadersParamsOK, error)

	GetMessageParams(params *GetMessageParamsParams, opts ...ClientOption) (*GetMessageParamsOK, error)

	ReleaseMessageParams(params *ReleaseMessageParamsParams, opts ...ClientOption) (*ReleaseMessageParamsOK, error)

	SendMessageParams(params *SendMessageParamsParams, opts ...ClientOption) (*SendMessageParamsOK, error)

	ThumbnailParams(params *ThumbnailParamsParams, opts ...ClientOption) (*ThumbnailParamsOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
	AttachmentParams gets message attachment

	This will return the attachment part using the appropriate Content-Type.

The ID can be set to `latest` to reference the latest message.
*/
func (a *Client) AttachmentParams(params *AttachmentParamsParams, opts ...ClientOption) (*AttachmentParamsOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewAttachmentParamsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "AttachmentParams",
		Method:             "GET",
		PathPattern:        "/api/v1/message/{ID}/part/{PartID}",
		ProducesMediaTypes: []string{"application/*", "image/*", "text/*"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &AttachmentParamsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*AttachmentParamsOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for AttachmentParams: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
	DownloadRawParams gets message source

	Returns the full email source as plain text.

The ID can be set to `latest` to return the latest message source.
*/
func (a *Client) DownloadRawParams(params *DownloadRawParamsParams, opts ...ClientOption) (*DownloadRawParamsOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewDownloadRawParamsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "DownloadRawParams",
		Method:             "GET",
		PathPattern:        "/api/v1/message/{ID}/raw",
		ProducesMediaTypes: []string{"text/plain"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &DownloadRawParamsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*DownloadRawParamsOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for DownloadRawParams: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
	GetHeadersParams gets message headers

	Returns the message headers as an array. Note that header keys are returned alphabetically.

The ID can be set to `latest` to return the latest message headers.
*/
func (a *Client) GetHeadersParams(params *GetHeadersParamsParams, opts ...ClientOption) (*GetHeadersParamsOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetHeadersParamsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetHeadersParams",
		Method:             "GET",
		PathPattern:        "/api/v1/message/{ID}/headers",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetHeadersParamsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetHeadersParamsOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetHeadersParams: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
	GetMessageParams gets message summary

	Returns the summary of a message, marking the message as read.

The ID can be set to `latest` to return the latest message.
*/
func (a *Client) GetMessageParams(params *GetMessageParamsParams, opts ...ClientOption) (*GetMessageParamsOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetMessageParamsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetMessageParams",
		Method:             "GET",
		PathPattern:        "/api/v1/message/{ID}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetMessageParamsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetMessageParamsOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetMessageParams: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
	ReleaseMessageParams releases message

	Release a message via a pre-configured external SMTP server. This is only enabled if message relaying has been configured.

The ID can be set to `latest` to reference the latest message.
*/
func (a *Client) ReleaseMessageParams(params *ReleaseMessageParamsParams, opts ...ClientOption) (*ReleaseMessageParamsOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewReleaseMessageParamsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "ReleaseMessageParams",
		Method:             "POST",
		PathPattern:        "/api/v1/message/{ID}/release",
		ProducesMediaTypes: []string{"text/plain"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &ReleaseMessageParamsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*ReleaseMessageParamsOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for ReleaseMessageParams: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
SendMessageParams sends a message

Send a message via the HTTP API.
*/
func (a *Client) SendMessageParams(params *SendMessageParamsParams, opts ...ClientOption) (*SendMessageParamsOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewSendMessageParamsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "SendMessageParams",
		Method:             "POST",
		PathPattern:        "/api/v1/send",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &SendMessageParamsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*SendMessageParamsOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for SendMessageParams: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
	ThumbnailParams gets an attachment image thumbnail

	This will return a cropped 180x120 JPEG thumbnail of an image attachment.

If the image is smaller than 180x120 then the image is padded. If the attachment is not an image then a blank image is returned.

The ID can be set to `latest` to return the latest message.
*/
func (a *Client) ThumbnailParams(params *ThumbnailParamsParams, opts ...ClientOption) (*ThumbnailParamsOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewThumbnailParamsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "ThumbnailParams",
		Method:             "GET",
		PathPattern:        "/api/v1/message/{ID}/part/{PartID}/thumb",
		ProducesMediaTypes: []string{"image/jpeg"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &ThumbnailParamsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*ThumbnailParamsOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for ThumbnailParams: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
