// Code generated by go-swagger; DO NOT EDIT.

package message

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ReleaseMessageParamsReader is a Reader for the ReleaseMessageParams structure.
type ReleaseMessageParamsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ReleaseMessageParamsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewReleaseMessageParamsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewReleaseMessageParamsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewReleaseMessageParamsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /api/v1/message/{ID}/release] ReleaseMessageParams", response, response.Code())
	}
}

// NewReleaseMessageParamsOK creates a ReleaseMessageParamsOK with default headers values
func NewReleaseMessageParamsOK() *ReleaseMessageParamsOK {
	return &ReleaseMessageParamsOK{}
}

/*
ReleaseMessageParamsOK describes a response with status code 200, with default header values.

Plain text "ok" response
*/
type ReleaseMessageParamsOK struct {
	Payload string
}

// IsSuccess returns true when this release message params o k response has a 2xx status code
func (o *ReleaseMessageParamsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this release message params o k response has a 3xx status code
func (o *ReleaseMessageParamsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this release message params o k response has a 4xx status code
func (o *ReleaseMessageParamsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this release message params o k response has a 5xx status code
func (o *ReleaseMessageParamsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this release message params o k response a status code equal to that given
func (o *ReleaseMessageParamsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the release message params o k response
func (o *ReleaseMessageParamsOK) Code() int {
	return 200
}

func (o *ReleaseMessageParamsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/message/{ID}/release][%d] releaseMessageParamsOK %s", 200, payload)
}

func (o *ReleaseMessageParamsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/message/{ID}/release][%d] releaseMessageParamsOK %s", 200, payload)
}

func (o *ReleaseMessageParamsOK) GetPayload() string {
	return o.Payload
}

func (o *ReleaseMessageParamsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewReleaseMessageParamsBadRequest creates a ReleaseMessageParamsBadRequest with default headers values
func NewReleaseMessageParamsBadRequest() *ReleaseMessageParamsBadRequest {
	return &ReleaseMessageParamsBadRequest{}
}

/*
	ReleaseMessageParamsBadRequest describes a response with status code 400, with default header values.

	Server error will return with a 400 status code

with the error message in the body
*/
type ReleaseMessageParamsBadRequest struct {
	Payload string
}

// IsSuccess returns true when this release message params bad request response has a 2xx status code
func (o *ReleaseMessageParamsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this release message params bad request response has a 3xx status code
func (o *ReleaseMessageParamsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this release message params bad request response has a 4xx status code
func (o *ReleaseMessageParamsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this release message params bad request response has a 5xx status code
func (o *ReleaseMessageParamsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this release message params bad request response a status code equal to that given
func (o *ReleaseMessageParamsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the release message params bad request response
func (o *ReleaseMessageParamsBadRequest) Code() int {
	return 400
}

func (o *ReleaseMessageParamsBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/message/{ID}/release][%d] releaseMessageParamsBadRequest %s", 400, payload)
}

func (o *ReleaseMessageParamsBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/message/{ID}/release][%d] releaseMessageParamsBadRequest %s", 400, payload)
}

func (o *ReleaseMessageParamsBadRequest) GetPayload() string {
	return o.Payload
}

func (o *ReleaseMessageParamsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewReleaseMessageParamsNotFound creates a ReleaseMessageParamsNotFound with default headers values
func NewReleaseMessageParamsNotFound() *ReleaseMessageParamsNotFound {
	return &ReleaseMessageParamsNotFound{}
}

/*
ReleaseMessageParamsNotFound describes a response with status code 404, with default header values.

Not found error will return a 404 status code
*/
type ReleaseMessageParamsNotFound struct {
	Payload string
}

// IsSuccess returns true when this release message params not found response has a 2xx status code
func (o *ReleaseMessageParamsNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this release message params not found response has a 3xx status code
func (o *ReleaseMessageParamsNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this release message params not found response has a 4xx status code
func (o *ReleaseMessageParamsNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this release message params not found response has a 5xx status code
func (o *ReleaseMessageParamsNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this release message params not found response a status code equal to that given
func (o *ReleaseMessageParamsNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the release message params not found response
func (o *ReleaseMessageParamsNotFound) Code() int {
	return 404
}

func (o *ReleaseMessageParamsNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/message/{ID}/release][%d] releaseMessageParamsNotFound %s", 404, payload)
}

func (o *ReleaseMessageParamsNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/message/{ID}/release][%d] releaseMessageParamsNotFound %s", 404, payload)
}

func (o *ReleaseMessageParamsNotFound) GetPayload() string {
	return o.Payload
}

func (o *ReleaseMessageParamsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

/*
ReleaseMessageParamsBody release message params body
swagger:model ReleaseMessageParamsBody
*/
type ReleaseMessageParamsBody struct {

	// Array of email addresses to relay the message to
	// Example: ["user1@example.com","user2@example.com"]
	// Required: true
	To []string `json:"To"`
}

// Validate validates this release message params body
func (o *ReleaseMessageParamsBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateTo(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ReleaseMessageParamsBody) validateTo(formats strfmt.Registry) error {

	if err := validate.Required("Body"+"."+"To", "body", o.To); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this release message params body based on context it is used
func (o *ReleaseMessageParamsBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *ReleaseMessageParamsBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ReleaseMessageParamsBody) UnmarshalBinary(b []byte) error {
	var res ReleaseMessageParamsBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
