// Code generated by go-swagger; DO NOT EDIT.

package message

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SendMessageParamsReader is a Reader for the SendMessageParams structure.
type SendMessageParamsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SendMessageParamsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewSendMessageParamsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewSendMessageParamsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /api/v1/send] SendMessageParams", response, response.Code())
	}
}

// NewSendMessageParamsOK creates a SendMessageParamsOK with default headers values
func NewSendMessageParamsOK() *SendMessageParamsOK {
	return &SendMessageParamsOK{}
}

/*
SendMessageParamsOK describes a response with status code 200, with default header values.

Confirmation message for HTTP send API
*/
type SendMessageParamsOK struct {
	Payload *SendMessageParamsOKBody
}

// IsSuccess returns true when this send message params o k response has a 2xx status code
func (o *SendMessageParamsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this send message params o k response has a 3xx status code
func (o *SendMessageParamsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this send message params o k response has a 4xx status code
func (o *SendMessageParamsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this send message params o k response has a 5xx status code
func (o *SendMessageParamsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this send message params o k response a status code equal to that given
func (o *SendMessageParamsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the send message params o k response
func (o *SendMessageParamsOK) Code() int {
	return 200
}

func (o *SendMessageParamsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/send][%d] sendMessageParamsOK %s", 200, payload)
}

func (o *SendMessageParamsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/send][%d] sendMessageParamsOK %s", 200, payload)
}

func (o *SendMessageParamsOK) GetPayload() *SendMessageParamsOKBody {
	return o.Payload
}

func (o *SendMessageParamsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(SendMessageParamsOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewSendMessageParamsBadRequest creates a SendMessageParamsBadRequest with default headers values
func NewSendMessageParamsBadRequest() *SendMessageParamsBadRequest {
	return &SendMessageParamsBadRequest{}
}

/*
SendMessageParamsBadRequest describes a response with status code 400, with default header values.

JSON error response
*/
type SendMessageParamsBadRequest struct {
	Payload *SendMessageParamsBadRequestBody
}

// IsSuccess returns true when this send message params bad request response has a 2xx status code
func (o *SendMessageParamsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this send message params bad request response has a 3xx status code
func (o *SendMessageParamsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this send message params bad request response has a 4xx status code
func (o *SendMessageParamsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this send message params bad request response has a 5xx status code
func (o *SendMessageParamsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this send message params bad request response a status code equal to that given
func (o *SendMessageParamsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the send message params bad request response
func (o *SendMessageParamsBadRequest) Code() int {
	return 400
}

func (o *SendMessageParamsBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/send][%d] sendMessageParamsBadRequest %s", 400, payload)
}

func (o *SendMessageParamsBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/send][%d] sendMessageParamsBadRequest %s", 400, payload)
}

func (o *SendMessageParamsBadRequest) GetPayload() *SendMessageParamsBadRequestBody {
	return o.Payload
}

func (o *SendMessageParamsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(SendMessageParamsBadRequestBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

/*
SendMessageParamsBadRequestBody send message params bad request body
swagger:model SendMessageParamsBadRequestBody
*/
type SendMessageParamsBadRequestBody struct {

	// Error message
	// Example: invalid format
	Error string `json:"Error,omitempty"`
}

// Validate validates this send message params bad request body
func (o *SendMessageParamsBadRequestBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this send message params bad request body based on context it is used
func (o *SendMessageParamsBadRequestBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *SendMessageParamsBadRequestBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *SendMessageParamsBadRequestBody) UnmarshalBinary(b []byte) error {
	var res SendMessageParamsBadRequestBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
SendMessageParamsBody send message params body
swagger:model SendMessageParamsBody
*/
type SendMessageParamsBody struct {

	// Attachments
	Attachments []*SendMessageParamsParamsBodyAttachmentsItems0 `json:"Attachments"`

	// Bcc recipients email addresses only
	// Example: ["jack@example.com"]
	Bcc []string `json:"Bcc"`

	// Cc recipients
	Cc []*SendMessageParamsParamsBodyCcItems0 `json:"Cc"`

	// from
	// Required: true
	From *SendMessageParamsParamsBodyFrom `json:"From"`

	// Message body (HTML)
	// Example: \u003cdiv style=\"text-align:center\"\u003e\u003cp style=\"font-family: arial; font-size: 24px;\"\u003eMailpit is \u003cb\u003eawesome\u003c/b\u003e!\u003c/p\u003e\u003cp\u003e\u003cimg src=\"cid:mailpit-logo\" /\u003e\u003c/p\u003e\u003c/div\u003e
	HTML string `json:"HTML,omitempty"`

	// Optional headers in {"key":"value"} format
	// Example: {"X-IP":"1.2.3.4"}
	Headers map[string]string `json:"Headers,omitempty"`

	// Optional Reply-To recipients
	ReplyTo []*SendMessageParamsParamsBodyReplyToItems0 `json:"ReplyTo"`

	// Subject
	// Example: Mailpit message via the HTTP API
	Subject string `json:"Subject,omitempty"`

	// Mailpit tags
	// Example: ["Tag 1","Tag 2"]
	Tags []string `json:"Tags"`

	// Message body (text)
	// Example: Mailpit is awesome!
	Text string `json:"Text,omitempty"`

	// "To" recipients
	To []*SendMessageParamsParamsBodyToItems0 `json:"To"`
}

// Validate validates this send message params body
func (o *SendMessageParamsBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateAttachments(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateCc(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateFrom(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateReplyTo(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateTo(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *SendMessageParamsBody) validateAttachments(formats strfmt.Registry) error {
	if swag.IsZero(o.Attachments) { // not required
		return nil
	}

	for i := 0; i < len(o.Attachments); i++ {
		if swag.IsZero(o.Attachments[i]) { // not required
			continue
		}

		if o.Attachments[i] != nil {
			if err := o.Attachments[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("Body" + "." + "Attachments" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("Body" + "." + "Attachments" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (o *SendMessageParamsBody) validateCc(formats strfmt.Registry) error {
	if swag.IsZero(o.Cc) { // not required
		return nil
	}

	for i := 0; i < len(o.Cc); i++ {
		if swag.IsZero(o.Cc[i]) { // not required
			continue
		}

		if o.Cc[i] != nil {
			if err := o.Cc[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("Body" + "." + "Cc" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("Body" + "." + "Cc" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (o *SendMessageParamsBody) validateFrom(formats strfmt.Registry) error {

	if err := validate.Required("Body"+"."+"From", "body", o.From); err != nil {
		return err
	}

	if o.From != nil {
		if err := o.From.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("Body" + "." + "From")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("Body" + "." + "From")
			}

			return err
		}
	}

	return nil
}

func (o *SendMessageParamsBody) validateReplyTo(formats strfmt.Registry) error {
	if swag.IsZero(o.ReplyTo) { // not required
		return nil
	}

	for i := 0; i < len(o.ReplyTo); i++ {
		if swag.IsZero(o.ReplyTo[i]) { // not required
			continue
		}

		if o.ReplyTo[i] != nil {
			if err := o.ReplyTo[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("Body" + "." + "ReplyTo" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("Body" + "." + "ReplyTo" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (o *SendMessageParamsBody) validateTo(formats strfmt.Registry) error {
	if swag.IsZero(o.To) { // not required
		return nil
	}

	for i := 0; i < len(o.To); i++ {
		if swag.IsZero(o.To[i]) { // not required
			continue
		}

		if o.To[i] != nil {
			if err := o.To[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("Body" + "." + "To" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("Body" + "." + "To" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this send message params body based on the context it is used
func (o *SendMessageParamsBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateAttachments(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidateCc(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidateFrom(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidateReplyTo(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidateTo(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *SendMessageParamsBody) contextValidateAttachments(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Attachments); i++ {

		if o.Attachments[i] != nil {

			if swag.IsZero(o.Attachments[i]) { // not required
				return nil
			}

			if err := o.Attachments[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("Body" + "." + "Attachments" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("Body" + "." + "Attachments" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (o *SendMessageParamsBody) contextValidateCc(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Cc); i++ {

		if o.Cc[i] != nil {

			if swag.IsZero(o.Cc[i]) { // not required
				return nil
			}

			if err := o.Cc[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("Body" + "." + "Cc" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("Body" + "." + "Cc" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (o *SendMessageParamsBody) contextValidateFrom(ctx context.Context, formats strfmt.Registry) error {

	if o.From != nil {

		if err := o.From.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("Body" + "." + "From")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("Body" + "." + "From")
			}

			return err
		}
	}

	return nil
}

func (o *SendMessageParamsBody) contextValidateReplyTo(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.ReplyTo); i++ {

		if o.ReplyTo[i] != nil {

			if swag.IsZero(o.ReplyTo[i]) { // not required
				return nil
			}

			if err := o.ReplyTo[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("Body" + "." + "ReplyTo" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("Body" + "." + "ReplyTo" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (o *SendMessageParamsBody) contextValidateTo(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.To); i++ {

		if o.To[i] != nil {

			if swag.IsZero(o.To[i]) { // not required
				return nil
			}

			if err := o.To[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("Body" + "." + "To" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("Body" + "." + "To" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *SendMessageParamsBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *SendMessageParamsBody) UnmarshalBinary(b []byte) error {
	var res SendMessageParamsBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
SendMessageParamsOKBody send message params o k body
swagger:model SendMessageParamsOKBody
*/
type SendMessageParamsOKBody struct {

	// Database ID
	// Example: iAfZVVe2UQfNSG5BAjgYwa
	ID string `json:"ID,omitempty"`
}

// Validate validates this send message params o k body
func (o *SendMessageParamsOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this send message params o k body based on context it is used
func (o *SendMessageParamsOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *SendMessageParamsOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *SendMessageParamsOKBody) UnmarshalBinary(b []byte) error {
	var res SendMessageParamsOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
SendMessageParamsParamsBodyAttachmentsItems0 send message params params body attachments items0
swagger:model SendMessageParamsParamsBodyAttachmentsItems0
*/
type SendMessageParamsParamsBodyAttachmentsItems0 struct {

	// Base64-encoded string of the file content
	// Example: iVBORw0KGgoAAAANSUhEUgAAAEEAAAA8CAMAAAAOlSdoAAAACXBIWXMAAAHrAAAB6wGM2bZBAAAAS1BMVEVHcEwRfnUkZ2gAt4UsSF8At4UtSV4At4YsSV4At4YsSV8At4YsSV4At4YsSV4sSV4At4YsSV4At4YtSV4At4YsSV4At4YtSV8At4YsUWYNAAAAGHRSTlMAAwoXGiktRE5dbnd7kpOlr7zJ0d3h8PD8PCSRAAACWUlEQVR42pXT4ZaqIBSG4W9rhqQYocG+/ys9Y0Z0Br+x3j8zaxUPewFh65K+7yrIMeIY4MT3wPfEJCidKXEMnLaVkxDiELiMz4WEOAZSFghxBIypCOlKiAMgXfIqTnBgSm8CIQ6BImxEUxEckClVQiHGj4Ba4AQHikAIClwTE9KtIghAhUJwoLkmLnCiAHJLRKgIMsEtVUKbBUIwoAg2C4QgQBE6l4VCnApBgSKYLLApCnCa0+96AEMW2BQcmC+Pr3nfp7o5Exy49gIADcIqUELGfeA+bp93LmAJp8QJoEcN3C7NY3sbVANixMyI0nku20/n5/ZRf3KI2k6JEDWQtxcbdGuAqu3TAXG+/799Oyyas1B1MnMiA+XyxHp9q0PUKGPiRAau1fZbLRZV09wZcT8/gHk8QQAxXn8VgaDqcUmU6O/r28nbVwXAqca2mRNtPAF5+zoP2MeN9Fy4NgC6RfcbgE7XITBRYTtOE3U3C2DVff7pk+PkUxgAbvtnPXJaD6DxulMLwOhPS/M3MQkgg1ZFrIXnmfaZoOfpKiFgzeZD/WuKqQEGrfJYkyWf6vlG3xUgTuscnkNkQsb599q124kdpMUjCa/XARHs1gZymVtGt3wLkiFv8rUgTxitYCex5EVGec0Y9VmoDTFBSQte2TfXGXlf7hbdaUM9Sk7fisEN9qfBBTK+FZcvM9fQSdkl2vj4W2oX/bRogO3XasiNH7R0eW7fgRM834ImTg+Lg6BEnx4vz81rhr+MYPBBQg1v8GndEOrthxaCTxNAOut8WKLGZQl+MPz88Q9tAO/hVuSeqQAAAABJRU5ErkJggg==
	// Required: true
	Content *string `json:"Content"`

	// Optional Content-ID (`cid`) for attachment.
	// If this field is set then the file is attached inline.
	// Example: mailpit-logo
	ContentID string `json:"ContentID,omitempty"`

	// Optional Content Type for the the attachment.
	// If this field is not set (or empty) then the content type is automatically detected.
	// Example: image/png
	ContentType string `json:"ContentType,omitempty"`

	// Filename
	// Example: mailpit.png
	// Required: true
	Filename *string `json:"Filename"`
}

// Validate validates this send message params params body attachments items0
func (o *SendMessageParamsParamsBodyAttachmentsItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateContent(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateFilename(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *SendMessageParamsParamsBodyAttachmentsItems0) validateContent(formats strfmt.Registry) error {

	if err := validate.Required("Content", "body", o.Content); err != nil {
		return err
	}

	return nil
}

func (o *SendMessageParamsParamsBodyAttachmentsItems0) validateFilename(formats strfmt.Registry) error {

	if err := validate.Required("Filename", "body", o.Filename); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this send message params params body attachments items0 based on context it is used
func (o *SendMessageParamsParamsBodyAttachmentsItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *SendMessageParamsParamsBodyAttachmentsItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *SendMessageParamsParamsBodyAttachmentsItems0) UnmarshalBinary(b []byte) error {
	var res SendMessageParamsParamsBodyAttachmentsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
SendMessageParamsParamsBodyCcItems0 send message params params body cc items0
swagger:model SendMessageParamsParamsBodyCcItems0
*/
type SendMessageParamsParamsBodyCcItems0 struct {

	// Email address
	// Example: manager@example.com
	// Required: true
	Email *string `json:"Email"`

	// Optional name
	// Example: Manager
	Name string `json:"Name,omitempty"`
}

// Validate validates this send message params params body cc items0
func (o *SendMessageParamsParamsBodyCcItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateEmail(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *SendMessageParamsParamsBodyCcItems0) validateEmail(formats strfmt.Registry) error {

	if err := validate.Required("Email", "body", o.Email); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this send message params params body cc items0 based on context it is used
func (o *SendMessageParamsParamsBodyCcItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *SendMessageParamsParamsBodyCcItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *SendMessageParamsParamsBodyCcItems0) UnmarshalBinary(b []byte) error {
	var res SendMessageParamsParamsBodyCcItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
SendMessageParamsParamsBodyFrom "From" recipient
swagger:model SendMessageParamsParamsBodyFrom
*/
type SendMessageParamsParamsBodyFrom struct {

	// Email address
	// Example: john@example.com
	// Required: true
	Email *string `json:"Email"`

	// Optional name
	// Example: John Doe
	Name string `json:"Name,omitempty"`
}

// Validate validates this send message params params body from
func (o *SendMessageParamsParamsBodyFrom) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateEmail(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *SendMessageParamsParamsBodyFrom) validateEmail(formats strfmt.Registry) error {

	if err := validate.Required("Body"+"."+"From"+"."+"Email", "body", o.Email); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this send message params params body from based on context it is used
func (o *SendMessageParamsParamsBodyFrom) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *SendMessageParamsParamsBodyFrom) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *SendMessageParamsParamsBodyFrom) UnmarshalBinary(b []byte) error {
	var res SendMessageParamsParamsBodyFrom
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
SendMessageParamsParamsBodyReplyToItems0 send message params params body reply to items0
swagger:model SendMessageParamsParamsBodyReplyToItems0
*/
type SendMessageParamsParamsBodyReplyToItems0 struct {

	// Email address
	// Example: secretary@example.com
	// Required: true
	Email *string `json:"Email"`

	// Optional name
	// Example: Secretary
	Name string `json:"Name,omitempty"`
}

// Validate validates this send message params params body reply to items0
func (o *SendMessageParamsParamsBodyReplyToItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateEmail(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *SendMessageParamsParamsBodyReplyToItems0) validateEmail(formats strfmt.Registry) error {

	if err := validate.Required("Email", "body", o.Email); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this send message params params body reply to items0 based on context it is used
func (o *SendMessageParamsParamsBodyReplyToItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *SendMessageParamsParamsBodyReplyToItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *SendMessageParamsParamsBodyReplyToItems0) UnmarshalBinary(b []byte) error {
	var res SendMessageParamsParamsBodyReplyToItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
SendMessageParamsParamsBodyToItems0 send message params params body to items0
swagger:model SendMessageParamsParamsBodyToItems0
*/
type SendMessageParamsParamsBodyToItems0 struct {

	// Email address
	// Example: jane@example.com
	// Required: true
	Email *string `json:"Email"`

	// Optional name
	// Example: Jane Doe
	Name string `json:"Name,omitempty"`
}

// Validate validates this send message params params body to items0
func (o *SendMessageParamsParamsBodyToItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateEmail(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *SendMessageParamsParamsBodyToItems0) validateEmail(formats strfmt.Registry) error {

	if err := validate.Required("Email", "body", o.Email); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this send message params params body to items0 based on context it is used
func (o *SendMessageParamsParamsBodyToItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *SendMessageParamsParamsBodyToItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *SendMessageParamsParamsBodyToItems0) UnmarshalBinary(b []byte) error {
	var res SendMessageParamsParamsBodyToItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
