// Code generated by go-swagger; DO NOT EDIT.

package message

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewSendMessageParamsParams creates a new SendMessageParamsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSendMessageParamsParams() *SendMessageParamsParams {
	return &SendMessageParamsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSendMessageParamsParamsWithTimeout creates a new SendMessageParamsParams object
// with the ability to set a timeout on a request.
func NewSendMessageParamsParamsWithTimeout(timeout time.Duration) *SendMessageParamsParams {
	return &SendMessageParamsParams{
		timeout: timeout,
	}
}

// NewSendMessageParamsParamsWithContext creates a new SendMessageParamsParams object
// with the ability to set a context for a request.
func NewSendMessageParamsParamsWithContext(ctx context.Context) *SendMessageParamsParams {
	return &SendMessageParamsParams{
		Context: ctx,
	}
}

// NewSendMessageParamsParamsWithHTTPClient creates a new SendMessageParamsParams object
// with the ability to set a custom HTTPClient for a request.
func NewSendMessageParamsParamsWithHTTPClient(client *http.Client) *SendMessageParamsParams {
	return &SendMessageParamsParams{
		HTTPClient: client,
	}
}

/*
SendMessageParamsParams contains all the parameters to send to the API endpoint

	for the send message params operation.

	Typically these are written to a http.Request.
*/
type SendMessageParamsParams struct {

	// Body.
	Body SendMessageParamsBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the send message params params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SendMessageParamsParams) WithDefaults() *SendMessageParamsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the send message params params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SendMessageParamsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the send message params params
func (o *SendMessageParamsParams) WithTimeout(timeout time.Duration) *SendMessageParamsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the send message params params
func (o *SendMessageParamsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the send message params params
func (o *SendMessageParamsParams) WithContext(ctx context.Context) *SendMessageParamsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the send message params params
func (o *SendMessageParamsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the send message params params
func (o *SendMessageParamsParams) WithHTTPClient(client *http.Client) *SendMessageParamsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the send message params params
func (o *SendMessageParamsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the send message params params
func (o *SendMessageParamsParams) WithBody(body SendMessageParamsBody) *SendMessageParamsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the send message params params
func (o *SendMessageParamsParams) SetBody(body SendMessageParamsBody) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *SendMessageParamsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
