// Code generated by go-swagger; DO NOT EDIT.

package message

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewThumbnailParamsParams creates a new ThumbnailParamsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewThumbnailParamsParams() *ThumbnailParamsParams {
	return &ThumbnailParamsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewThumbnailParamsParamsWithTimeout creates a new ThumbnailParamsParams object
// with the ability to set a timeout on a request.
func NewThumbnailParamsParamsWithTimeout(timeout time.Duration) *ThumbnailParamsParams {
	return &ThumbnailParamsParams{
		timeout: timeout,
	}
}

// NewThumbnailParamsParamsWithContext creates a new ThumbnailParamsParams object
// with the ability to set a context for a request.
func NewThumbnailParamsParamsWithContext(ctx context.Context) *ThumbnailParamsParams {
	return &ThumbnailParamsParams{
		Context: ctx,
	}
}

// NewThumbnailParamsParamsWithHTTPClient creates a new ThumbnailParamsParams object
// with the ability to set a custom HTTPClient for a request.
func NewThumbnailParamsParamsWithHTTPClient(client *http.Client) *ThumbnailParamsParams {
	return &ThumbnailParamsParams{
		HTTPClient: client,
	}
}

/*
ThumbnailParamsParams contains all the parameters to send to the API endpoint

	for the thumbnail params operation.

	Typically these are written to a http.Request.
*/
type ThumbnailParamsParams struct {

	/* ID.

	   Message database ID or "latest"
	*/
	ID string

	/* PartID.

	   Attachment part ID
	*/
	PartID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the thumbnail params params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ThumbnailParamsParams) WithDefaults() *ThumbnailParamsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the thumbnail params params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ThumbnailParamsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the thumbnail params params
func (o *ThumbnailParamsParams) WithTimeout(timeout time.Duration) *ThumbnailParamsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the thumbnail params params
func (o *ThumbnailParamsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the thumbnail params params
func (o *ThumbnailParamsParams) WithContext(ctx context.Context) *ThumbnailParamsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the thumbnail params params
func (o *ThumbnailParamsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the thumbnail params params
func (o *ThumbnailParamsParams) WithHTTPClient(client *http.Client) *ThumbnailParamsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the thumbnail params params
func (o *ThumbnailParamsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the thumbnail params params
func (o *ThumbnailParamsParams) WithID(id string) *ThumbnailParamsParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the thumbnail params params
func (o *ThumbnailParamsParams) SetID(id string) {
	o.ID = id
}

// WithPartID adds the partID to the thumbnail params params
func (o *ThumbnailParamsParams) WithPartID(partID string) *ThumbnailParamsParams {
	o.SetPartID(partID)
	return o
}

// SetPartID adds the partId to the thumbnail params params
func (o *ThumbnailParamsParams) SetPartID(partID string) {
	o.PartID = partID
}

// WriteToRequest writes these params to a swagger request
func (o *ThumbnailParamsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param ID
	if err := r.SetPathParam("ID", o.ID); err != nil {
		return err
	}

	// path param PartID
	if err := r.SetPathParam("PartID", o.PartID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
