// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AppInformation AppInformation struct
//
// swagger:model AppInformation
type AppInformation struct {

	// Database path
	Database string `json:"Database,omitempty"`

	// Database size in bytes
	DatabaseSize uint64 `json:"DatabaseSize,omitempty"`

	// Latest Mailpit version
	LatestVersion string `json:"LatestVersion,omitempty"`

	// Total number of messages in the database
	Messages uint64 `json:"Messages,omitempty"`

	// runtime stats
	RuntimeStats *AppInformationRuntimeStats `json:"RuntimeStats,omitempty"`

	// Tags and message totals per tag
	Tags map[string]int64 `json:"Tags,omitempty"`

	// Total number of messages in the database
	Unread uint64 `json:"Unread,omitempty"`

	// Current Mailpit version
	Version string `json:"Version,omitempty"`
}

// Validate validates this app information
func (m *AppInformation) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRuntimeStats(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AppInformation) validateRuntimeStats(formats strfmt.Registry) error {
	if swag.IsZero(m.RuntimeStats) { // not required
		return nil
	}

	if m.RuntimeStats != nil {
		if err := m.RuntimeStats.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("RuntimeStats")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("RuntimeStats")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this app information based on the context it is used
func (m *AppInformation) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateRuntimeStats(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AppInformation) contextValidateRuntimeStats(ctx context.Context, formats strfmt.Registry) error {

	if m.RuntimeStats != nil {

		if swag.IsZero(m.RuntimeStats) { // not required
			return nil
		}

		if err := m.RuntimeStats.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("RuntimeStats")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("RuntimeStats")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *AppInformation) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AppInformation) UnmarshalBinary(b []byte) error {
	var res AppInformation
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// AppInformationRuntimeStats Runtime statistics
//
// swagger:model AppInformationRuntimeStats
type AppInformationRuntimeStats struct {

	// Current memory usage in bytes
	Memory uint64 `json:"Memory,omitempty"`

	// Database runtime messages deleted
	MessagesDeleted uint64 `json:"MessagesDeleted,omitempty"`

	// Accepted runtime SMTP messages
	SMTPAccepted uint64 `json:"SMTPAccepted,omitempty"`

	// Total runtime accepted messages size in bytes
	SMTPAcceptedSize uint64 `json:"SMTPAcceptedSize,omitempty"`

	// Ignored runtime SMTP messages (when using --ignore-duplicate-ids)
	SMTPIgnored uint64 `json:"SMTPIgnored,omitempty"`

	// Rejected runtime SMTP messages
	SMTPRejected uint64 `json:"SMTPRejected,omitempty"`

	// Mailpit server uptime in seconds
	Uptime uint64 `json:"Uptime,omitempty"`
}

// Validate validates this app information runtime stats
func (m *AppInformationRuntimeStats) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this app information runtime stats based on context it is used
func (m *AppInformationRuntimeStats) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AppInformationRuntimeStats) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AppInformationRuntimeStats) UnmarshalBinary(b []byte) error {
	var res AppInformationRuntimeStats
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
