// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ListUnsubscribe ListUnsubscribe contains a summary of List-Unsubscribe & List-Unsubscribe-Post headers
// including validation of the link structure
//
// swagger:model ListUnsubscribe
type ListUnsubscribe struct {

	// Validation errors (if any)
	Errors string `json:"Errors,omitempty"`

	// List-Unsubscribe header value
	Header string `json:"Header,omitempty"`

	// List-Unsubscribe-Post value (if set)
	HeaderPost string `json:"HeaderPost,omitempty"`

	// Detected links, maximum one email and one HTTP(S) link
	Links []string `json:"Links"`
}

// Validate validates this list unsubscribe
func (m *ListUnsubscribe) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this list unsubscribe based on context it is used
func (m *ListUnsubscribe) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ListUnsubscribe) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ListUnsubscribe) UnmarshalBinary(b []byte) error {
	var res ListUnsubscribe
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
