// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Message Message data excluding physical attachments
//
// swagger:model Message
type Message struct {

	// Message attachments
	Attachments []*Attachment `json:"Attachments"`

	// Bcc addresses
	Bcc []*Address `json:"Bcc"`

	// Cc addresses
	Cc []*Address `json:"Cc"`

	// Message RFC3339Nano date & time (if set), else date & time received
	// ([extended RFC3339](https://tools.ietf.org/html/rfc3339#section-5.6) format with optional nano seconds)
	// Format: date-time
	Date strfmt.DateTime `json:"Date,omitempty"`

	// from
	From *Address `json:"From,omitempty"`

	// Message body HTML
	HTML string `json:"HTML,omitempty"`

	// Database ID
	ID string `json:"ID,omitempty"`

	// Inline message attachments
	Inline []*Attachment `json:"Inline"`

	// list unsubscribe
	ListUnsubscribe *ListUnsubscribe `json:"ListUnsubscribe,omitempty"`

	// Message ID
	MessageID string `json:"MessageID,omitempty"`

	// ReplyTo addresses
	ReplyTo []*Address `json:"ReplyTo"`

	// Return-Path
	ReturnPath string `json:"ReturnPath,omitempty"`

	// Message size in bytes
	Size uint64 `json:"Size,omitempty"`

	// Message subject
	Subject string `json:"Subject,omitempty"`

	// Message tags
	Tags []string `json:"Tags"`

	// Message body text
	Text string `json:"Text,omitempty"`

	// To addresses
	To []*Address `json:"To"`

	// Username used for authentication (if provided) with the SMTP or Send API
	Username string `json:"Username,omitempty"`
}

// Validate validates this message
func (m *Message) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAttachments(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateBcc(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCc(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFrom(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateInline(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateListUnsubscribe(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateReplyTo(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTo(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Message) validateAttachments(formats strfmt.Registry) error {
	if swag.IsZero(m.Attachments) { // not required
		return nil
	}

	for i := 0; i < len(m.Attachments); i++ {
		if swag.IsZero(m.Attachments[i]) { // not required
			continue
		}

		if m.Attachments[i] != nil {
			if err := m.Attachments[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("Attachments" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("Attachments" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *Message) validateBcc(formats strfmt.Registry) error {
	if swag.IsZero(m.Bcc) { // not required
		return nil
	}

	for i := 0; i < len(m.Bcc); i++ {
		if swag.IsZero(m.Bcc[i]) { // not required
			continue
		}

		if m.Bcc[i] != nil {
			if err := m.Bcc[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("Bcc" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("Bcc" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *Message) validateCc(formats strfmt.Registry) error {
	if swag.IsZero(m.Cc) { // not required
		return nil
	}

	for i := 0; i < len(m.Cc); i++ {
		if swag.IsZero(m.Cc[i]) { // not required
			continue
		}

		if m.Cc[i] != nil {
			if err := m.Cc[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("Cc" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("Cc" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *Message) validateDate(formats strfmt.Registry) error {
	if swag.IsZero(m.Date) { // not required
		return nil
	}

	if err := validate.FormatOf("Date", "body", "date-time", m.Date.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *Message) validateFrom(formats strfmt.Registry) error {
	if swag.IsZero(m.From) { // not required
		return nil
	}

	if m.From != nil {
		if err := m.From.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("From")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("From")
			}

			return err
		}
	}

	return nil
}

func (m *Message) validateInline(formats strfmt.Registry) error {
	if swag.IsZero(m.Inline) { // not required
		return nil
	}

	for i := 0; i < len(m.Inline); i++ {
		if swag.IsZero(m.Inline[i]) { // not required
			continue
		}

		if m.Inline[i] != nil {
			if err := m.Inline[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("Inline" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("Inline" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *Message) validateListUnsubscribe(formats strfmt.Registry) error {
	if swag.IsZero(m.ListUnsubscribe) { // not required
		return nil
	}

	if m.ListUnsubscribe != nil {
		if err := m.ListUnsubscribe.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("ListUnsubscribe")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("ListUnsubscribe")
			}

			return err
		}
	}

	return nil
}

func (m *Message) validateReplyTo(formats strfmt.Registry) error {
	if swag.IsZero(m.ReplyTo) { // not required
		return nil
	}

	for i := 0; i < len(m.ReplyTo); i++ {
		if swag.IsZero(m.ReplyTo[i]) { // not required
			continue
		}

		if m.ReplyTo[i] != nil {
			if err := m.ReplyTo[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("ReplyTo" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("ReplyTo" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *Message) validateTo(formats strfmt.Registry) error {
	if swag.IsZero(m.To) { // not required
		return nil
	}

	for i := 0; i < len(m.To); i++ {
		if swag.IsZero(m.To[i]) { // not required
			continue
		}

		if m.To[i] != nil {
			if err := m.To[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("To" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("To" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this message based on the context it is used
func (m *Message) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAttachments(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateBcc(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateCc(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateFrom(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateInline(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateListUnsubscribe(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateReplyTo(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateTo(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Message) contextValidateAttachments(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Attachments); i++ {

		if m.Attachments[i] != nil {

			if swag.IsZero(m.Attachments[i]) { // not required
				return nil
			}

			if err := m.Attachments[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("Attachments" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("Attachments" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *Message) contextValidateBcc(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Bcc); i++ {

		if m.Bcc[i] != nil {

			if swag.IsZero(m.Bcc[i]) { // not required
				return nil
			}

			if err := m.Bcc[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("Bcc" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("Bcc" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *Message) contextValidateCc(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Cc); i++ {

		if m.Cc[i] != nil {

			if swag.IsZero(m.Cc[i]) { // not required
				return nil
			}

			if err := m.Cc[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("Cc" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("Cc" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *Message) contextValidateFrom(ctx context.Context, formats strfmt.Registry) error {

	if m.From != nil {

		if swag.IsZero(m.From) { // not required
			return nil
		}

		if err := m.From.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("From")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("From")
			}

			return err
		}
	}

	return nil
}

func (m *Message) contextValidateInline(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Inline); i++ {

		if m.Inline[i] != nil {

			if swag.IsZero(m.Inline[i]) { // not required
				return nil
			}

			if err := m.Inline[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("Inline" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("Inline" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *Message) contextValidateListUnsubscribe(ctx context.Context, formats strfmt.Registry) error {

	if m.ListUnsubscribe != nil {

		if swag.IsZero(m.ListUnsubscribe) { // not required
			return nil
		}

		if err := m.ListUnsubscribe.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("ListUnsubscribe")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("ListUnsubscribe")
			}

			return err
		}
	}

	return nil
}

func (m *Message) contextValidateReplyTo(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.ReplyTo); i++ {

		if m.ReplyTo[i] != nil {

			if swag.IsZero(m.ReplyTo[i]) { // not required
				return nil
			}

			if err := m.ReplyTo[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("ReplyTo" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("ReplyTo" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *Message) contextValidateTo(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.To); i++ {

		if m.To[i] != nil {

			if swag.IsZero(m.To[i]) { // not required
				return nil
			}

			if err := m.To[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("To" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("To" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *Message) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Message) UnmarshalBinary(b []byte) error {
	var res Message
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
