// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// MessageHeadersResponse Message headers
//
// swagger:model messageHeadersResponse
type MessageHeadersResponse map[string][]string

// Validate validates this message headers response
func (m MessageHeadersResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this message headers response based on context it is used
func (m MessageHeadersResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
