// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Score Score struct
//
// swagger:model Score
type Score struct {

	// Number of matches in the document
	Found int64 `json:"Found,omitempty"`

	// Total percentage partially supported
	Partial float32 `json:"Partial,omitempty"`

	// Total percentage supported
	Supported float32 `json:"Supported,omitempty"`

	// Total percentage unsupported
	Unsupported float32 `json:"Unsupported,omitempty"`
}

// Validate validates this score
func (m *Score) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this score based on context it is used
func (m *Score) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Score) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Score) UnmarshalBinary(b []byte) error {
	var res Score
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
