// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Total Total weighted result for all scores
//
// swagger:model Total
type Total struct {

	// Total number of HTML nodes detected in message
	Nodes int64 `json:"Nodes,omitempty"`

	// Overall percentage partially supported
	Partial float32 `json:"Partial,omitempty"`

	// Overall percentage supported
	Supported float32 `json:"Supported,omitempty"`

	// Total number of tests done
	Tests int64 `json:"Tests,omitempty"`

	// Overall percentage unsupported
	Unsupported float32 `json:"Unsupported,omitempty"`
}

// Validate validates this total
func (m *Total) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this total based on context it is used
func (m *Total) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Total) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Total) UnmarshalBinary(b []byte) error {
	var res Total
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
