// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Trigger Trigger for Chaos
//
// swagger:model Trigger
type Trigger struct {

	// SMTP error code to return. The value must range from 400 to 599.
	// Example: 451
	// Required: true
	ErrorCode *int64 `json:"ErrorCode"`

	// Probability (chance) of triggering the error. The value must range from 0 to 100.
	// Example: 5
	// Required: true
	Probability *int64 `json:"Probability"`
}

// Validate validates this trigger
func (m *Trigger) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateErrorCode(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProbability(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Trigger) validateErrorCode(formats strfmt.Registry) error {

	if err := validate.Required("ErrorCode", "body", m.ErrorCode); err != nil {
		return err
	}

	return nil
}

func (m *Trigger) validateProbability(formats strfmt.Registry) error {

	if err := validate.Required("Probability", "body", m.Probability); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this trigger based on context it is used
func (m *Trigger) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Trigger) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Trigger) UnmarshalBinary(b []byte) error {
	var res Trigger
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
