// Code generated by go-swagger; DO NOT EDIT.

package testing

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/otakakot/sample-mailpit/pkg/mailpit/models"
)

// GetChaosReader is a Reader for the GetChaos structure.
type GetChaosReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetChaosReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetChaosOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetChaosBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/v1/chaos] getChaos", response, response.Code())
	}
}

// NewGetChaosOK creates a GetChaosOK with default headers values
func NewGetChaosOK() *GetChaosOK {
	return &GetChaosOK{}
}

/*
GetChaosOK describes a response with status code 200, with default header values.

Response for the Chaos triggers configuration
*/
type GetChaosOK struct {
	Payload *models.Triggers
}

// IsSuccess returns true when this get chaos o k response has a 2xx status code
func (o *GetChaosOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get chaos o k response has a 3xx status code
func (o *GetChaosOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get chaos o k response has a 4xx status code
func (o *GetChaosOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get chaos o k response has a 5xx status code
func (o *GetChaosOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get chaos o k response a status code equal to that given
func (o *GetChaosOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get chaos o k response
func (o *GetChaosOK) Code() int {
	return 200
}

func (o *GetChaosOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/chaos][%d] getChaosOK %s", 200, payload)
}

func (o *GetChaosOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/chaos][%d] getChaosOK %s", 200, payload)
}

func (o *GetChaosOK) GetPayload() *models.Triggers {
	return o.Payload
}

func (o *GetChaosOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Triggers)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetChaosBadRequest creates a GetChaosBadRequest with default headers values
func NewGetChaosBadRequest() *GetChaosBadRequest {
	return &GetChaosBadRequest{}
}

/*
	GetChaosBadRequest describes a response with status code 400, with default header values.

	Server error will return with a 400 status code

with the error message in the body
*/
type GetChaosBadRequest struct {
	Payload string
}

// IsSuccess returns true when this get chaos bad request response has a 2xx status code
func (o *GetChaosBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get chaos bad request response has a 3xx status code
func (o *GetChaosBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get chaos bad request response has a 4xx status code
func (o *GetChaosBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get chaos bad request response has a 5xx status code
func (o *GetChaosBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get chaos bad request response a status code equal to that given
func (o *GetChaosBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get chaos bad request response
func (o *GetChaosBadRequest) Code() int {
	return 400
}

func (o *GetChaosBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/chaos][%d] getChaosBadRequest %s", 400, payload)
}

func (o *GetChaosBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/chaos][%d] getChaosBadRequest %s", 400, payload)
}

func (o *GetChaosBadRequest) GetPayload() string {
	return o.Payload
}

func (o *GetChaosBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
