// Code generated by go-swagger; DO NOT EDIT.

package testing

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetChaosParams creates a new GetChaosParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetChaosParams() *GetChaosParams {
	return &GetChaosParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetChaosParamsWithTimeout creates a new GetChaosParams object
// with the ability to set a timeout on a request.
func NewGetChaosParamsWithTimeout(timeout time.Duration) *GetChaosParams {
	return &GetChaosParams{
		timeout: timeout,
	}
}

// NewGetChaosParamsWithContext creates a new GetChaosParams object
// with the ability to set a context for a request.
func NewGetChaosParamsWithContext(ctx context.Context) *GetChaosParams {
	return &GetChaosParams{
		Context: ctx,
	}
}

// NewGetChaosParamsWithHTTPClient creates a new GetChaosParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetChaosParamsWithHTTPClient(client *http.Client) *GetChaosParams {
	return &GetChaosParams{
		HTTPClient: client,
	}
}

/*
GetChaosParams contains all the parameters to send to the API endpoint

	for the get chaos operation.

	Typically these are written to a http.Request.
*/
type GetChaosParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get chaos params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetChaosParams) WithDefaults() *GetChaosParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get chaos params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetChaosParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get chaos params
func (o *GetChaosParams) WithTimeout(timeout time.Duration) *GetChaosParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get chaos params
func (o *GetChaosParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get chaos params
func (o *GetChaosParams) WithContext(ctx context.Context) *GetChaosParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get chaos params
func (o *GetChaosParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get chaos params
func (o *GetChaosParams) WithHTTPClient(client *http.Client) *GetChaosParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get chaos params
func (o *GetChaosParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetChaosParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
