// Code generated by go-swagger; DO NOT EDIT.

package testing

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetMessageHTMLParamsParams creates a new GetMessageHTMLParamsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetMessageHTMLParamsParams() *GetMessageHTMLParamsParams {
	return &GetMessageHTMLParamsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetMessageHTMLParamsParamsWithTimeout creates a new GetMessageHTMLParamsParams object
// with the ability to set a timeout on a request.
func NewGetMessageHTMLParamsParamsWithTimeout(timeout time.Duration) *GetMessageHTMLParamsParams {
	return &GetMessageHTMLParamsParams{
		timeout: timeout,
	}
}

// NewGetMessageHTMLParamsParamsWithContext creates a new GetMessageHTMLParamsParams object
// with the ability to set a context for a request.
func NewGetMessageHTMLParamsParamsWithContext(ctx context.Context) *GetMessageHTMLParamsParams {
	return &GetMessageHTMLParamsParams{
		Context: ctx,
	}
}

// NewGetMessageHTMLParamsParamsWithHTTPClient creates a new GetMessageHTMLParamsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetMessageHTMLParamsParamsWithHTTPClient(client *http.Client) *GetMessageHTMLParamsParams {
	return &GetMessageHTMLParamsParams{
		HTTPClient: client,
	}
}

/*
GetMessageHTMLParamsParams contains all the parameters to send to the API endpoint

	for the get message HTML params operation.

	Typically these are written to a http.Request.
*/
type GetMessageHTMLParamsParams struct {

	/* ID.

	   Message database ID or "latest"
	*/
	ID string

	/* Embed.

	     If this is route is to be embedded in an iframe, set embed to `1` in the URL to add `target="_blank"` and `rel="noreferrer noopener"` to all links.

	In addition, a small script will be added to the end of the document to post (postMessage()) the height of the document back to the parent window for optional iframe height resizing.

	Note that this will also *transform* the message into a full HTML document (if it isn't already), so this option is useful for viewing but not programmatic testing.
	*/
	Embed *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get message HTML params params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetMessageHTMLParamsParams) WithDefaults() *GetMessageHTMLParamsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get message HTML params params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetMessageHTMLParamsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get message HTML params params
func (o *GetMessageHTMLParamsParams) WithTimeout(timeout time.Duration) *GetMessageHTMLParamsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get message HTML params params
func (o *GetMessageHTMLParamsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get message HTML params params
func (o *GetMessageHTMLParamsParams) WithContext(ctx context.Context) *GetMessageHTMLParamsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get message HTML params params
func (o *GetMessageHTMLParamsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get message HTML params params
func (o *GetMessageHTMLParamsParams) WithHTTPClient(client *http.Client) *GetMessageHTMLParamsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get message HTML params params
func (o *GetMessageHTMLParamsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get message HTML params params
func (o *GetMessageHTMLParamsParams) WithID(id string) *GetMessageHTMLParamsParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get message HTML params params
func (o *GetMessageHTMLParamsParams) SetID(id string) {
	o.ID = id
}

// WithEmbed adds the embed to the get message HTML params params
func (o *GetMessageHTMLParamsParams) WithEmbed(embed *string) *GetMessageHTMLParamsParams {
	o.SetEmbed(embed)
	return o
}

// SetEmbed adds the embed to the get message HTML params params
func (o *GetMessageHTMLParamsParams) SetEmbed(embed *string) {
	o.Embed = embed
}

// WriteToRequest writes these params to a swagger request
func (o *GetMessageHTMLParamsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param ID
	if err := r.SetPathParam("ID", o.ID); err != nil {
		return err
	}

	if o.Embed != nil {

		// query param embed
		var qrEmbed string

		if o.Embed != nil {
			qrEmbed = *o.Embed
		}
		qEmbed := qrEmbed
		if qEmbed != "" {

			if err := r.SetQueryParam("embed", qEmbed); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
