// Code generated by go-swagger; DO NOT EDIT.

package testing

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetMessageTextParamsReader is a Reader for the GetMessageTextParams structure.
type GetMessageTextParamsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetMessageTextParamsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetMessageTextParamsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetMessageTextParamsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetMessageTextParamsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /view/{ID}.txt] GetMessageTextParams", response, response.Code())
	}
}

// NewGetMessageTextParamsOK creates a GetMessageTextParamsOK with default headers values
func NewGetMessageTextParamsOK() *GetMessageTextParamsOK {
	return &GetMessageTextParamsOK{}
}

/*
GetMessageTextParamsOK describes a response with status code 200, with default header values.

Plain text response
*/
type GetMessageTextParamsOK struct {
	Payload string
}

// IsSuccess returns true when this get message text params o k response has a 2xx status code
func (o *GetMessageTextParamsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get message text params o k response has a 3xx status code
func (o *GetMessageTextParamsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get message text params o k response has a 4xx status code
func (o *GetMessageTextParamsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get message text params o k response has a 5xx status code
func (o *GetMessageTextParamsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get message text params o k response a status code equal to that given
func (o *GetMessageTextParamsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get message text params o k response
func (o *GetMessageTextParamsOK) Code() int {
	return 200
}

func (o *GetMessageTextParamsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /view/{ID}.txt][%d] getMessageTextParamsOK %s", 200, payload)
}

func (o *GetMessageTextParamsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /view/{ID}.txt][%d] getMessageTextParamsOK %s", 200, payload)
}

func (o *GetMessageTextParamsOK) GetPayload() string {
	return o.Payload
}

func (o *GetMessageTextParamsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetMessageTextParamsBadRequest creates a GetMessageTextParamsBadRequest with default headers values
func NewGetMessageTextParamsBadRequest() *GetMessageTextParamsBadRequest {
	return &GetMessageTextParamsBadRequest{}
}

/*
	GetMessageTextParamsBadRequest describes a response with status code 400, with default header values.

	Server error will return with a 400 status code

with the error message in the body
*/
type GetMessageTextParamsBadRequest struct {
	Payload string
}

// IsSuccess returns true when this get message text params bad request response has a 2xx status code
func (o *GetMessageTextParamsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get message text params bad request response has a 3xx status code
func (o *GetMessageTextParamsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get message text params bad request response has a 4xx status code
func (o *GetMessageTextParamsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get message text params bad request response has a 5xx status code
func (o *GetMessageTextParamsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get message text params bad request response a status code equal to that given
func (o *GetMessageTextParamsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get message text params bad request response
func (o *GetMessageTextParamsBadRequest) Code() int {
	return 400
}

func (o *GetMessageTextParamsBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /view/{ID}.txt][%d] getMessageTextParamsBadRequest %s", 400, payload)
}

func (o *GetMessageTextParamsBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /view/{ID}.txt][%d] getMessageTextParamsBadRequest %s", 400, payload)
}

func (o *GetMessageTextParamsBadRequest) GetPayload() string {
	return o.Payload
}

func (o *GetMessageTextParamsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetMessageTextParamsNotFound creates a GetMessageTextParamsNotFound with default headers values
func NewGetMessageTextParamsNotFound() *GetMessageTextParamsNotFound {
	return &GetMessageTextParamsNotFound{}
}

/*
GetMessageTextParamsNotFound describes a response with status code 404, with default header values.

Not found error will return a 404 status code
*/
type GetMessageTextParamsNotFound struct {
	Payload string
}

// IsSuccess returns true when this get message text params not found response has a 2xx status code
func (o *GetMessageTextParamsNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get message text params not found response has a 3xx status code
func (o *GetMessageTextParamsNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get message text params not found response has a 4xx status code
func (o *GetMessageTextParamsNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get message text params not found response has a 5xx status code
func (o *GetMessageTextParamsNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get message text params not found response a status code equal to that given
func (o *GetMessageTextParamsNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get message text params not found response
func (o *GetMessageTextParamsNotFound) Code() int {
	return 404
}

func (o *GetMessageTextParamsNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /view/{ID}.txt][%d] getMessageTextParamsNotFound %s", 404, payload)
}

func (o *GetMessageTextParamsNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /view/{ID}.txt][%d] getMessageTextParamsNotFound %s", 404, payload)
}

func (o *GetMessageTextParamsNotFound) GetPayload() string {
	return o.Payload
}

func (o *GetMessageTextParamsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
