// Code generated by go-swagger; DO NOT EDIT.

package testing

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetMessageHTMLParamsReader is a Reader for the GetMessageHTMLParams structure.
type GetMessageHTMLParamsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetMessageHTMLParamsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetMessageHTMLParamsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetMessageHTMLParamsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetMessageHTMLParamsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /view/{ID}.html] GetMessageHTMLParams", response, response.Code())
	}
}

// NewGetMessageHTMLParamsOK creates a GetMessageHTMLParamsOK with default headers values
func NewGetMessageHTMLParamsOK() *GetMessageHTMLParamsOK {
	return &GetMessageHTMLParamsOK{}
}

/*
GetMessageHTMLParamsOK describes a response with status code 200, with default header values.

HTML response
*/
type GetMessageHTMLParamsOK struct {
	Payload string
}

// IsSuccess returns true when this get message Html params o k response has a 2xx status code
func (o *GetMessageHTMLParamsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get message Html params o k response has a 3xx status code
func (o *GetMessageHTMLParamsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get message Html params o k response has a 4xx status code
func (o *GetMessageHTMLParamsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get message Html params o k response has a 5xx status code
func (o *GetMessageHTMLParamsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get message Html params o k response a status code equal to that given
func (o *GetMessageHTMLParamsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get message Html params o k response
func (o *GetMessageHTMLParamsOK) Code() int {
	return 200
}

func (o *GetMessageHTMLParamsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /view/{ID}.html][%d] getMessageHtmlParamsOK %s", 200, payload)
}

func (o *GetMessageHTMLParamsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /view/{ID}.html][%d] getMessageHtmlParamsOK %s", 200, payload)
}

func (o *GetMessageHTMLParamsOK) GetPayload() string {
	return o.Payload
}

func (o *GetMessageHTMLParamsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetMessageHTMLParamsBadRequest creates a GetMessageHTMLParamsBadRequest with default headers values
func NewGetMessageHTMLParamsBadRequest() *GetMessageHTMLParamsBadRequest {
	return &GetMessageHTMLParamsBadRequest{}
}

/*
	GetMessageHTMLParamsBadRequest describes a response with status code 400, with default header values.

	Server error will return with a 400 status code

with the error message in the body
*/
type GetMessageHTMLParamsBadRequest struct {
	Payload string
}

// IsSuccess returns true when this get message Html params bad request response has a 2xx status code
func (o *GetMessageHTMLParamsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get message Html params bad request response has a 3xx status code
func (o *GetMessageHTMLParamsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get message Html params bad request response has a 4xx status code
func (o *GetMessageHTMLParamsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get message Html params bad request response has a 5xx status code
func (o *GetMessageHTMLParamsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get message Html params bad request response a status code equal to that given
func (o *GetMessageHTMLParamsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get message Html params bad request response
func (o *GetMessageHTMLParamsBadRequest) Code() int {
	return 400
}

func (o *GetMessageHTMLParamsBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /view/{ID}.html][%d] getMessageHtmlParamsBadRequest %s", 400, payload)
}

func (o *GetMessageHTMLParamsBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /view/{ID}.html][%d] getMessageHtmlParamsBadRequest %s", 400, payload)
}

func (o *GetMessageHTMLParamsBadRequest) GetPayload() string {
	return o.Payload
}

func (o *GetMessageHTMLParamsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetMessageHTMLParamsNotFound creates a GetMessageHTMLParamsNotFound with default headers values
func NewGetMessageHTMLParamsNotFound() *GetMessageHTMLParamsNotFound {
	return &GetMessageHTMLParamsNotFound{}
}

/*
GetMessageHTMLParamsNotFound describes a response with status code 404, with default header values.

Not found error will return a 404 status code
*/
type GetMessageHTMLParamsNotFound struct {
	Payload string
}

// IsSuccess returns true when this get message Html params not found response has a 2xx status code
func (o *GetMessageHTMLParamsNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get message Html params not found response has a 3xx status code
func (o *GetMessageHTMLParamsNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get message Html params not found response has a 4xx status code
func (o *GetMessageHTMLParamsNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get message Html params not found response has a 5xx status code
func (o *GetMessageHTMLParamsNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get message Html params not found response a status code equal to that given
func (o *GetMessageHTMLParamsNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get message Html params not found response
func (o *GetMessageHTMLParamsNotFound) Code() int {
	return 404
}

func (o *GetMessageHTMLParamsNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /view/{ID}.html][%d] getMessageHtmlParamsNotFound %s", 404, payload)
}

func (o *GetMessageHTMLParamsNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /view/{ID}.html][%d] getMessageHtmlParamsNotFound %s", 404, payload)
}

func (o *GetMessageHTMLParamsNotFound) GetPayload() string {
	return o.Payload
}

func (o *GetMessageHTMLParamsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
