// Code generated by go-swagger; DO NOT EDIT.

package testing

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/otakakot/sample-mailpit/pkg/mailpit/models"
)

// SetChaosParamsReader is a Reader for the SetChaosParams structure.
type SetChaosParamsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SetChaosParamsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewSetChaosParamsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewSetChaosParamsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[PUT /api/v1/chaos] setChaosParams", response, response.Code())
	}
}

// NewSetChaosParamsOK creates a SetChaosParamsOK with default headers values
func NewSetChaosParamsOK() *SetChaosParamsOK {
	return &SetChaosParamsOK{}
}

/*
SetChaosParamsOK describes a response with status code 200, with default header values.

Response for the Chaos triggers configuration
*/
type SetChaosParamsOK struct {
	Payload *models.Triggers
}

// IsSuccess returns true when this set chaos params o k response has a 2xx status code
func (o *SetChaosParamsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this set chaos params o k response has a 3xx status code
func (o *SetChaosParamsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this set chaos params o k response has a 4xx status code
func (o *SetChaosParamsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this set chaos params o k response has a 5xx status code
func (o *SetChaosParamsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this set chaos params o k response a status code equal to that given
func (o *SetChaosParamsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the set chaos params o k response
func (o *SetChaosParamsOK) Code() int {
	return 200
}

func (o *SetChaosParamsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/v1/chaos][%d] setChaosParamsOK %s", 200, payload)
}

func (o *SetChaosParamsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/v1/chaos][%d] setChaosParamsOK %s", 200, payload)
}

func (o *SetChaosParamsOK) GetPayload() *models.Triggers {
	return o.Payload
}

func (o *SetChaosParamsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Triggers)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewSetChaosParamsBadRequest creates a SetChaosParamsBadRequest with default headers values
func NewSetChaosParamsBadRequest() *SetChaosParamsBadRequest {
	return &SetChaosParamsBadRequest{}
}

/*
	SetChaosParamsBadRequest describes a response with status code 400, with default header values.

	Server error will return with a 400 status code

with the error message in the body
*/
type SetChaosParamsBadRequest struct {
	Payload string
}

// IsSuccess returns true when this set chaos params bad request response has a 2xx status code
func (o *SetChaosParamsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this set chaos params bad request response has a 3xx status code
func (o *SetChaosParamsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this set chaos params bad request response has a 4xx status code
func (o *SetChaosParamsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this set chaos params bad request response has a 5xx status code
func (o *SetChaosParamsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this set chaos params bad request response a status code equal to that given
func (o *SetChaosParamsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the set chaos params bad request response
func (o *SetChaosParamsBadRequest) Code() int {
	return 400
}

func (o *SetChaosParamsBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/v1/chaos][%d] setChaosParamsBadRequest %s", 400, payload)
}

func (o *SetChaosParamsBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/v1/chaos][%d] setChaosParamsBadRequest %s", 400, payload)
}

func (o *SetChaosParamsBadRequest) GetPayload() string {
	return o.Payload
}

func (o *SetChaosParamsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
