// Code generated by go-swagger; DO NOT EDIT.

package tags

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteTagParamsParams creates a new DeleteTagParamsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteTagParamsParams() *DeleteTagParamsParams {
	return &DeleteTagParamsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteTagParamsParamsWithTimeout creates a new DeleteTagParamsParams object
// with the ability to set a timeout on a request.
func NewDeleteTagParamsParamsWithTimeout(timeout time.Duration) *DeleteTagParamsParams {
	return &DeleteTagParamsParams{
		timeout: timeout,
	}
}

// NewDeleteTagParamsParamsWithContext creates a new DeleteTagParamsParams object
// with the ability to set a context for a request.
func NewDeleteTagParamsParamsWithContext(ctx context.Context) *DeleteTagParamsParams {
	return &DeleteTagParamsParams{
		Context: ctx,
	}
}

// NewDeleteTagParamsParamsWithHTTPClient creates a new DeleteTagParamsParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteTagParamsParamsWithHTTPClient(client *http.Client) *DeleteTagParamsParams {
	return &DeleteTagParamsParams{
		HTTPClient: client,
	}
}

/*
DeleteTagParamsParams contains all the parameters to send to the API endpoint

	for the delete tag params operation.

	Typically these are written to a http.Request.
*/
type DeleteTagParamsParams struct {

	/* Tag.

	   The url-encoded tag name to delete
	*/
	Tag string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete tag params params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteTagParamsParams) WithDefaults() *DeleteTagParamsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete tag params params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteTagParamsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete tag params params
func (o *DeleteTagParamsParams) WithTimeout(timeout time.Duration) *DeleteTagParamsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete tag params params
func (o *DeleteTagParamsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete tag params params
func (o *DeleteTagParamsParams) WithContext(ctx context.Context) *DeleteTagParamsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete tag params params
func (o *DeleteTagParamsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete tag params params
func (o *DeleteTagParamsParams) WithHTTPClient(client *http.Client) *DeleteTagParamsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete tag params params
func (o *DeleteTagParamsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTag adds the tag to the delete tag params params
func (o *DeleteTagParamsParams) WithTag(tag string) *DeleteTagParamsParams {
	o.SetTag(tag)
	return o
}

// SetTag adds the tag to the delete tag params params
func (o *DeleteTagParamsParams) SetTag(tag string) {
	o.Tag = tag
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteTagParamsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param Tag
	if err := r.SetPathParam("Tag", o.Tag); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
