// Code generated by go-swagger; DO NOT EDIT.

package tags

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteTagParamsReader is a Reader for the DeleteTagParams structure.
type DeleteTagParamsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteTagParamsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteTagParamsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteTagParamsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /api/v1/tags/{Tag}] DeleteTagParams", response, response.Code())
	}
}

// NewDeleteTagParamsOK creates a DeleteTagParamsOK with default headers values
func NewDeleteTagParamsOK() *DeleteTagParamsOK {
	return &DeleteTagParamsOK{}
}

/*
DeleteTagParamsOK describes a response with status code 200, with default header values.

Plain text "ok" response
*/
type DeleteTagParamsOK struct {
	Payload string
}

// IsSuccess returns true when this delete tag params o k response has a 2xx status code
func (o *DeleteTagParamsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete tag params o k response has a 3xx status code
func (o *DeleteTagParamsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete tag params o k response has a 4xx status code
func (o *DeleteTagParamsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete tag params o k response has a 5xx status code
func (o *DeleteTagParamsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete tag params o k response a status code equal to that given
func (o *DeleteTagParamsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the delete tag params o k response
func (o *DeleteTagParamsOK) Code() int {
	return 200
}

func (o *DeleteTagParamsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/v1/tags/{Tag}][%d] deleteTagParamsOK %s", 200, payload)
}

func (o *DeleteTagParamsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/v1/tags/{Tag}][%d] deleteTagParamsOK %s", 200, payload)
}

func (o *DeleteTagParamsOK) GetPayload() string {
	return o.Payload
}

func (o *DeleteTagParamsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDeleteTagParamsBadRequest creates a DeleteTagParamsBadRequest with default headers values
func NewDeleteTagParamsBadRequest() *DeleteTagParamsBadRequest {
	return &DeleteTagParamsBadRequest{}
}

/*
	DeleteTagParamsBadRequest describes a response with status code 400, with default header values.

	Server error will return with a 400 status code

with the error message in the body
*/
type DeleteTagParamsBadRequest struct {
	Payload string
}

// IsSuccess returns true when this delete tag params bad request response has a 2xx status code
func (o *DeleteTagParamsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete tag params bad request response has a 3xx status code
func (o *DeleteTagParamsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete tag params bad request response has a 4xx status code
func (o *DeleteTagParamsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete tag params bad request response has a 5xx status code
func (o *DeleteTagParamsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this delete tag params bad request response a status code equal to that given
func (o *DeleteTagParamsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the delete tag params bad request response
func (o *DeleteTagParamsBadRequest) Code() int {
	return 400
}

func (o *DeleteTagParamsBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/v1/tags/{Tag}][%d] deleteTagParamsBadRequest %s", 400, payload)
}

func (o *DeleteTagParamsBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/v1/tags/{Tag}][%d] deleteTagParamsBadRequest %s", 400, payload)
}

func (o *DeleteTagParamsBadRequest) GetPayload() string {
	return o.Payload
}

func (o *DeleteTagParamsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
