// Code generated by go-swagger; DO NOT EDIT.

package tags

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetAllTagsReader is a Reader for the GetAllTags structure.
type GetAllTagsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAllTagsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetAllTagsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetAllTagsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/v1/tags] GetAllTags", response, response.Code())
	}
}

// NewGetAllTagsOK creates a GetAllTagsOK with default headers values
func NewGetAllTagsOK() *GetAllTagsOK {
	return &GetAllTagsOK{}
}

/*
GetAllTagsOK describes a response with status code 200, with default header values.

Plain JSON array response
*/
type GetAllTagsOK struct {
	Payload []string
}

// IsSuccess returns true when this get all tags o k response has a 2xx status code
func (o *GetAllTagsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get all tags o k response has a 3xx status code
func (o *GetAllTagsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get all tags o k response has a 4xx status code
func (o *GetAllTagsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get all tags o k response has a 5xx status code
func (o *GetAllTagsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get all tags o k response a status code equal to that given
func (o *GetAllTagsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get all tags o k response
func (o *GetAllTagsOK) Code() int {
	return 200
}

func (o *GetAllTagsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/tags][%d] getAllTagsOK %s", 200, payload)
}

func (o *GetAllTagsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/tags][%d] getAllTagsOK %s", 200, payload)
}

func (o *GetAllTagsOK) GetPayload() []string {
	return o.Payload
}

func (o *GetAllTagsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAllTagsBadRequest creates a GetAllTagsBadRequest with default headers values
func NewGetAllTagsBadRequest() *GetAllTagsBadRequest {
	return &GetAllTagsBadRequest{}
}

/*
	GetAllTagsBadRequest describes a response with status code 400, with default header values.

	Server error will return with a 400 status code

with the error message in the body
*/
type GetAllTagsBadRequest struct {
	Payload string
}

// IsSuccess returns true when this get all tags bad request response has a 2xx status code
func (o *GetAllTagsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get all tags bad request response has a 3xx status code
func (o *GetAllTagsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get all tags bad request response has a 4xx status code
func (o *GetAllTagsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get all tags bad request response has a 5xx status code
func (o *GetAllTagsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get all tags bad request response a status code equal to that given
func (o *GetAllTagsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get all tags bad request response
func (o *GetAllTagsBadRequest) Code() int {
	return 400
}

func (o *GetAllTagsBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/tags][%d] getAllTagsBadRequest %s", 400, payload)
}

func (o *GetAllTagsBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/tags][%d] getAllTagsBadRequest %s", 400, payload)
}

func (o *GetAllTagsBadRequest) GetPayload() string {
	return o.Payload
}

func (o *GetAllTagsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
