// Code generated by go-swagger; DO NOT EDIT.

package tags

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// RenameTagParamsReader is a Reader for the RenameTagParams structure.
type RenameTagParamsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RenameTagParamsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewRenameTagParamsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewRenameTagParamsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[PUT /api/v1/tags/{Tag}] RenameTagParams", response, response.Code())
	}
}

// NewRenameTagParamsOK creates a RenameTagParamsOK with default headers values
func NewRenameTagParamsOK() *RenameTagParamsOK {
	return &RenameTagParamsOK{}
}

/*
RenameTagParamsOK describes a response with status code 200, with default header values.

Plain text "ok" response
*/
type RenameTagParamsOK struct {
	Payload string
}

// IsSuccess returns true when this rename tag params o k response has a 2xx status code
func (o *RenameTagParamsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this rename tag params o k response has a 3xx status code
func (o *RenameTagParamsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this rename tag params o k response has a 4xx status code
func (o *RenameTagParamsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this rename tag params o k response has a 5xx status code
func (o *RenameTagParamsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this rename tag params o k response a status code equal to that given
func (o *RenameTagParamsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the rename tag params o k response
func (o *RenameTagParamsOK) Code() int {
	return 200
}

func (o *RenameTagParamsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/v1/tags/{Tag}][%d] renameTagParamsOK %s", 200, payload)
}

func (o *RenameTagParamsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/v1/tags/{Tag}][%d] renameTagParamsOK %s", 200, payload)
}

func (o *RenameTagParamsOK) GetPayload() string {
	return o.Payload
}

func (o *RenameTagParamsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewRenameTagParamsBadRequest creates a RenameTagParamsBadRequest with default headers values
func NewRenameTagParamsBadRequest() *RenameTagParamsBadRequest {
	return &RenameTagParamsBadRequest{}
}

/*
	RenameTagParamsBadRequest describes a response with status code 400, with default header values.

	Server error will return with a 400 status code

with the error message in the body
*/
type RenameTagParamsBadRequest struct {
	Payload string
}

// IsSuccess returns true when this rename tag params bad request response has a 2xx status code
func (o *RenameTagParamsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this rename tag params bad request response has a 3xx status code
func (o *RenameTagParamsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this rename tag params bad request response has a 4xx status code
func (o *RenameTagParamsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this rename tag params bad request response has a 5xx status code
func (o *RenameTagParamsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this rename tag params bad request response a status code equal to that given
func (o *RenameTagParamsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the rename tag params bad request response
func (o *RenameTagParamsBadRequest) Code() int {
	return 400
}

func (o *RenameTagParamsBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/v1/tags/{Tag}][%d] renameTagParamsBadRequest %s", 400, payload)
}

func (o *RenameTagParamsBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/v1/tags/{Tag}][%d] renameTagParamsBadRequest %s", 400, payload)
}

func (o *RenameTagParamsBadRequest) GetPayload() string {
	return o.Payload
}

func (o *RenameTagParamsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

/*
RenameTagParamsBody rename tag params body
swagger:model RenameTagParamsBody
*/
type RenameTagParamsBody struct {

	// New name
	// Example: New name
	// Required: true
	Name *string `json:"Name"`
}

// Validate validates this rename tag params body
func (o *RenameTagParamsBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *RenameTagParamsBody) validateName(formats strfmt.Registry) error {

	if err := validate.Required("Body"+"."+"Name", "body", o.Name); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this rename tag params body based on context it is used
func (o *RenameTagParamsBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *RenameTagParamsBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *RenameTagParamsBody) UnmarshalBinary(b []byte) error {
	var res RenameTagParamsBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
