// Code generated by go-swagger; DO NOT EDIT.

package tags

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewRenameTagParamsParams creates a new RenameTagParamsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRenameTagParamsParams() *RenameTagParamsParams {
	return &RenameTagParamsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRenameTagParamsParamsWithTimeout creates a new RenameTagParamsParams object
// with the ability to set a timeout on a request.
func NewRenameTagParamsParamsWithTimeout(timeout time.Duration) *RenameTagParamsParams {
	return &RenameTagParamsParams{
		timeout: timeout,
	}
}

// NewRenameTagParamsParamsWithContext creates a new RenameTagParamsParams object
// with the ability to set a context for a request.
func NewRenameTagParamsParamsWithContext(ctx context.Context) *RenameTagParamsParams {
	return &RenameTagParamsParams{
		Context: ctx,
	}
}

// NewRenameTagParamsParamsWithHTTPClient creates a new RenameTagParamsParams object
// with the ability to set a custom HTTPClient for a request.
func NewRenameTagParamsParamsWithHTTPClient(client *http.Client) *RenameTagParamsParams {
	return &RenameTagParamsParams{
		HTTPClient: client,
	}
}

/*
RenameTagParamsParams contains all the parameters to send to the API endpoint

	for the rename tag params operation.

	Typically these are written to a http.Request.
*/
type RenameTagParamsParams struct {

	// Body.
	Body RenameTagParamsBody

	/* Tag.

	   The url-encoded tag name to rename
	*/
	Tag string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the rename tag params params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RenameTagParamsParams) WithDefaults() *RenameTagParamsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the rename tag params params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RenameTagParamsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the rename tag params params
func (o *RenameTagParamsParams) WithTimeout(timeout time.Duration) *RenameTagParamsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the rename tag params params
func (o *RenameTagParamsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the rename tag params params
func (o *RenameTagParamsParams) WithContext(ctx context.Context) *RenameTagParamsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the rename tag params params
func (o *RenameTagParamsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the rename tag params params
func (o *RenameTagParamsParams) WithHTTPClient(client *http.Client) *RenameTagParamsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the rename tag params params
func (o *RenameTagParamsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the rename tag params params
func (o *RenameTagParamsParams) WithBody(body RenameTagParamsBody) *RenameTagParamsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the rename tag params params
func (o *RenameTagParamsParams) SetBody(body RenameTagParamsBody) {
	o.Body = body
}

// WithTag adds the tag to the rename tag params params
func (o *RenameTagParamsParams) WithTag(tag string) *RenameTagParamsParams {
	o.SetTag(tag)
	return o
}

// SetTag adds the tag to the rename tag params params
func (o *RenameTagParamsParams) SetTag(tag string) {
	o.Tag = tag
}

// WriteToRequest writes these params to a swagger request
func (o *RenameTagParamsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param Tag
	if err := r.SetPathParam("Tag", o.Tag); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
