// Code generated by go-swagger; DO NOT EDIT.

package tags

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewSetTagsParamsParams creates a new SetTagsParamsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSetTagsParamsParams() *SetTagsParamsParams {
	return &SetTagsParamsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSetTagsParamsParamsWithTimeout creates a new SetTagsParamsParams object
// with the ability to set a timeout on a request.
func NewSetTagsParamsParamsWithTimeout(timeout time.Duration) *SetTagsParamsParams {
	return &SetTagsParamsParams{
		timeout: timeout,
	}
}

// NewSetTagsParamsParamsWithContext creates a new SetTagsParamsParams object
// with the ability to set a context for a request.
func NewSetTagsParamsParamsWithContext(ctx context.Context) *SetTagsParamsParams {
	return &SetTagsParamsParams{
		Context: ctx,
	}
}

// NewSetTagsParamsParamsWithHTTPClient creates a new SetTagsParamsParams object
// with the ability to set a custom HTTPClient for a request.
func NewSetTagsParamsParamsWithHTTPClient(client *http.Client) *SetTagsParamsParams {
	return &SetTagsParamsParams{
		HTTPClient: client,
	}
}

/*
SetTagsParamsParams contains all the parameters to send to the API endpoint

	for the set tags params operation.

	Typically these are written to a http.Request.
*/
type SetTagsParamsParams struct {

	// Body.
	Body SetTagsParamsBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the set tags params params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SetTagsParamsParams) WithDefaults() *SetTagsParamsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the set tags params params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SetTagsParamsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the set tags params params
func (o *SetTagsParamsParams) WithTimeout(timeout time.Duration) *SetTagsParamsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the set tags params params
func (o *SetTagsParamsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the set tags params params
func (o *SetTagsParamsParams) WithContext(ctx context.Context) *SetTagsParamsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the set tags params params
func (o *SetTagsParamsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the set tags params params
func (o *SetTagsParamsParams) WithHTTPClient(client *http.Client) *SetTagsParamsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the set tags params params
func (o *SetTagsParamsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the set tags params params
func (o *SetTagsParamsParams) WithBody(body SetTagsParamsBody) *SetTagsParamsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the set tags params params
func (o *SetTagsParamsParams) SetBody(body SetTagsParamsBody) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *SetTagsParamsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
