// Code generated by go-swagger; DO NOT EDIT.

package tags

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SetTagsParamsReader is a Reader for the SetTagsParams structure.
type SetTagsParamsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SetTagsParamsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewSetTagsParamsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewSetTagsParamsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[PUT /api/v1/tags] SetTagsParams", response, response.Code())
	}
}

// NewSetTagsParamsOK creates a SetTagsParamsOK with default headers values
func NewSetTagsParamsOK() *SetTagsParamsOK {
	return &SetTagsParamsOK{}
}

/*
SetTagsParamsOK describes a response with status code 200, with default header values.

Plain text "ok" response
*/
type SetTagsParamsOK struct {
	Payload string
}

// IsSuccess returns true when this set tags params o k response has a 2xx status code
func (o *SetTagsParamsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this set tags params o k response has a 3xx status code
func (o *SetTagsParamsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this set tags params o k response has a 4xx status code
func (o *SetTagsParamsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this set tags params o k response has a 5xx status code
func (o *SetTagsParamsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this set tags params o k response a status code equal to that given
func (o *SetTagsParamsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the set tags params o k response
func (o *SetTagsParamsOK) Code() int {
	return 200
}

func (o *SetTagsParamsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/v1/tags][%d] setTagsParamsOK %s", 200, payload)
}

func (o *SetTagsParamsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/v1/tags][%d] setTagsParamsOK %s", 200, payload)
}

func (o *SetTagsParamsOK) GetPayload() string {
	return o.Payload
}

func (o *SetTagsParamsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewSetTagsParamsBadRequest creates a SetTagsParamsBadRequest with default headers values
func NewSetTagsParamsBadRequest() *SetTagsParamsBadRequest {
	return &SetTagsParamsBadRequest{}
}

/*
	SetTagsParamsBadRequest describes a response with status code 400, with default header values.

	Server error will return with a 400 status code

with the error message in the body
*/
type SetTagsParamsBadRequest struct {
	Payload string
}

// IsSuccess returns true when this set tags params bad request response has a 2xx status code
func (o *SetTagsParamsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this set tags params bad request response has a 3xx status code
func (o *SetTagsParamsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this set tags params bad request response has a 4xx status code
func (o *SetTagsParamsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this set tags params bad request response has a 5xx status code
func (o *SetTagsParamsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this set tags params bad request response a status code equal to that given
func (o *SetTagsParamsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the set tags params bad request response
func (o *SetTagsParamsBadRequest) Code() int {
	return 400
}

func (o *SetTagsParamsBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/v1/tags][%d] setTagsParamsBadRequest %s", 400, payload)
}

func (o *SetTagsParamsBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/v1/tags][%d] setTagsParamsBadRequest %s", 400, payload)
}

func (o *SetTagsParamsBadRequest) GetPayload() string {
	return o.Payload
}

func (o *SetTagsParamsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

/*
SetTagsParamsBody set tags params body
swagger:model SetTagsParamsBody
*/
type SetTagsParamsBody struct {

	// Array of message database IDs
	// Example: ["4oRBnPtCXgAqZniRhzLNmS","hXayS6wnCgNnt6aFTvmOF6"]
	// Required: true
	IDs []string `json:"IDs"`

	// Array of tag names to set
	// Example: ["Tag 1","Tag 2"]
	// Required: true
	Tags []string `json:"Tags"`
}

// Validate validates this set tags params body
func (o *SetTagsParamsBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateIDs(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateTags(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *SetTagsParamsBody) validateIDs(formats strfmt.Registry) error {

	if err := validate.Required("Body"+"."+"IDs", "body", o.IDs); err != nil {
		return err
	}

	return nil
}

func (o *SetTagsParamsBody) validateTags(formats strfmt.Registry) error {

	if err := validate.Required("Body"+"."+"Tags", "body", o.Tags); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this set tags params body based on context it is used
func (o *SetTagsParamsBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *SetTagsParamsBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *SetTagsParamsBody) UnmarshalBinary(b []byte) error {
	var res SetTagsParamsBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
