// Code generated by go-swagger; DO NOT EDIT.

package other

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewHTMLCheckParamsParams creates a new HTMLCheckParamsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewHTMLCheckParamsParams() *HTMLCheckParamsParams {
	return &HTMLCheckParamsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewHTMLCheckParamsParamsWithTimeout creates a new HTMLCheckParamsParams object
// with the ability to set a timeout on a request.
func NewHTMLCheckParamsParamsWithTimeout(timeout time.Duration) *HTMLCheckParamsParams {
	return &HTMLCheckParamsParams{
		timeout: timeout,
	}
}

// NewHTMLCheckParamsParamsWithContext creates a new HTMLCheckParamsParams object
// with the ability to set a context for a request.
func NewHTMLCheckParamsParamsWithContext(ctx context.Context) *HTMLCheckParamsParams {
	return &HTMLCheckParamsParams{
		Context: ctx,
	}
}

// NewHTMLCheckParamsParamsWithHTTPClient creates a new HTMLCheckParamsParams object
// with the ability to set a custom HTTPClient for a request.
func NewHTMLCheckParamsParamsWithHTTPClient(client *http.Client) *HTMLCheckParamsParams {
	return &HTMLCheckParamsParams{
		HTTPClient: client,
	}
}

/*
HTMLCheckParamsParams contains all the parameters to send to the API endpoint

	for the HTML check params operation.

	Typically these are written to a http.Request.
*/
type HTMLCheckParamsParams struct {

	/* ID.

	   Message database ID or "latest"
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the HTML check params params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *HTMLCheckParamsParams) WithDefaults() *HTMLCheckParamsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the HTML check params params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *HTMLCheckParamsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the HTML check params params
func (o *HTMLCheckParamsParams) WithTimeout(timeout time.Duration) *HTMLCheckParamsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the HTML check params params
func (o *HTMLCheckParamsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the HTML check params params
func (o *HTMLCheckParamsParams) WithContext(ctx context.Context) *HTMLCheckParamsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the HTML check params params
func (o *HTMLCheckParamsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the HTML check params params
func (o *HTMLCheckParamsParams) WithHTTPClient(client *http.Client) *HTMLCheckParamsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the HTML check params params
func (o *HTMLCheckParamsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the HTML check params params
func (o *HTMLCheckParamsParams) WithID(id string) *HTMLCheckParamsParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the HTML check params params
func (o *HTMLCheckParamsParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *HTMLCheckParamsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param ID
	if err := r.SetPathParam("ID", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
