// Code generated by go-swagger; DO NOT EDIT.

package other

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/otakakot/sample-mailpit/pkg/mailpit/models"
)

// HTMLCheckParamsReader is a Reader for the HTMLCheckParams structure.
type HTMLCheckParamsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *HTMLCheckParamsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewHTMLCheckParamsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewHTMLCheckParamsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewHTMLCheckParamsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/v1/message/{ID}/html-check] HTMLCheckParams", response, response.Code())
	}
}

// NewHTMLCheckParamsOK creates a HTMLCheckParamsOK with default headers values
func NewHTMLCheckParamsOK() *HTMLCheckParamsOK {
	return &HTMLCheckParamsOK{}
}

/*
HTMLCheckParamsOK describes a response with status code 200, with default header values.

HTMLCheckResponse
*/
type HTMLCheckParamsOK struct {
	Payload *models.Response
}

// IsSuccess returns true when this html check params o k response has a 2xx status code
func (o *HTMLCheckParamsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this html check params o k response has a 3xx status code
func (o *HTMLCheckParamsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this html check params o k response has a 4xx status code
func (o *HTMLCheckParamsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this html check params o k response has a 5xx status code
func (o *HTMLCheckParamsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this html check params o k response a status code equal to that given
func (o *HTMLCheckParamsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the html check params o k response
func (o *HTMLCheckParamsOK) Code() int {
	return 200
}

func (o *HTMLCheckParamsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/message/{ID}/html-check][%d] htmlCheckParamsOK %s", 200, payload)
}

func (o *HTMLCheckParamsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/message/{ID}/html-check][%d] htmlCheckParamsOK %s", 200, payload)
}

func (o *HTMLCheckParamsOK) GetPayload() *models.Response {
	return o.Payload
}

func (o *HTMLCheckParamsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Response)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewHTMLCheckParamsBadRequest creates a HTMLCheckParamsBadRequest with default headers values
func NewHTMLCheckParamsBadRequest() *HTMLCheckParamsBadRequest {
	return &HTMLCheckParamsBadRequest{}
}

/*
	HTMLCheckParamsBadRequest describes a response with status code 400, with default header values.

	Server error will return with a 400 status code

with the error message in the body
*/
type HTMLCheckParamsBadRequest struct {
	Payload string
}

// IsSuccess returns true when this html check params bad request response has a 2xx status code
func (o *HTMLCheckParamsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this html check params bad request response has a 3xx status code
func (o *HTMLCheckParamsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this html check params bad request response has a 4xx status code
func (o *HTMLCheckParamsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this html check params bad request response has a 5xx status code
func (o *HTMLCheckParamsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this html check params bad request response a status code equal to that given
func (o *HTMLCheckParamsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the html check params bad request response
func (o *HTMLCheckParamsBadRequest) Code() int {
	return 400
}

func (o *HTMLCheckParamsBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/message/{ID}/html-check][%d] htmlCheckParamsBadRequest %s", 400, payload)
}

func (o *HTMLCheckParamsBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/message/{ID}/html-check][%d] htmlCheckParamsBadRequest %s", 400, payload)
}

func (o *HTMLCheckParamsBadRequest) GetPayload() string {
	return o.Payload
}

func (o *HTMLCheckParamsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewHTMLCheckParamsNotFound creates a HTMLCheckParamsNotFound with default headers values
func NewHTMLCheckParamsNotFound() *HTMLCheckParamsNotFound {
	return &HTMLCheckParamsNotFound{}
}

/*
HTMLCheckParamsNotFound describes a response with status code 404, with default header values.

Not found error will return a 404 status code
*/
type HTMLCheckParamsNotFound struct {
	Payload string
}

// IsSuccess returns true when this html check params not found response has a 2xx status code
func (o *HTMLCheckParamsNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this html check params not found response has a 3xx status code
func (o *HTMLCheckParamsNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this html check params not found response has a 4xx status code
func (o *HTMLCheckParamsNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this html check params not found response has a 5xx status code
func (o *HTMLCheckParamsNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this html check params not found response a status code equal to that given
func (o *HTMLCheckParamsNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the html check params not found response
func (o *HTMLCheckParamsNotFound) Code() int {
	return 404
}

func (o *HTMLCheckParamsNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/message/{ID}/html-check][%d] htmlCheckParamsNotFound %s", 404, payload)
}

func (o *HTMLCheckParamsNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/message/{ID}/html-check][%d] htmlCheckParamsNotFound %s", 404, payload)
}

func (o *HTMLCheckParamsNotFound) GetPayload() string {
	return o.Payload
}

func (o *HTMLCheckParamsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
