// Code generated by go-swagger; DO NOT EDIT.

package other

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewLinkCheckParamsParams creates a new LinkCheckParamsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewLinkCheckParamsParams() *LinkCheckParamsParams {
	return &LinkCheckParamsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewLinkCheckParamsParamsWithTimeout creates a new LinkCheckParamsParams object
// with the ability to set a timeout on a request.
func NewLinkCheckParamsParamsWithTimeout(timeout time.Duration) *LinkCheckParamsParams {
	return &LinkCheckParamsParams{
		timeout: timeout,
	}
}

// NewLinkCheckParamsParamsWithContext creates a new LinkCheckParamsParams object
// with the ability to set a context for a request.
func NewLinkCheckParamsParamsWithContext(ctx context.Context) *LinkCheckParamsParams {
	return &LinkCheckParamsParams{
		Context: ctx,
	}
}

// NewLinkCheckParamsParamsWithHTTPClient creates a new LinkCheckParamsParams object
// with the ability to set a custom HTTPClient for a request.
func NewLinkCheckParamsParamsWithHTTPClient(client *http.Client) *LinkCheckParamsParams {
	return &LinkCheckParamsParams{
		HTTPClient: client,
	}
}

/*
LinkCheckParamsParams contains all the parameters to send to the API endpoint

	for the link check params operation.

	Typically these are written to a http.Request.
*/
type LinkCheckParamsParams struct {

	/* ID.

	   Message database ID or "latest"
	*/
	ID string

	/* Follow.

	   Follow redirects

	   Default: "false"
	*/
	Follow *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the link check params params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *LinkCheckParamsParams) WithDefaults() *LinkCheckParamsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the link check params params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *LinkCheckParamsParams) SetDefaults() {
	var (
		followDefault = string("false")
	)

	val := LinkCheckParamsParams{
		Follow: &followDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the link check params params
func (o *LinkCheckParamsParams) WithTimeout(timeout time.Duration) *LinkCheckParamsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the link check params params
func (o *LinkCheckParamsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the link check params params
func (o *LinkCheckParamsParams) WithContext(ctx context.Context) *LinkCheckParamsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the link check params params
func (o *LinkCheckParamsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the link check params params
func (o *LinkCheckParamsParams) WithHTTPClient(client *http.Client) *LinkCheckParamsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the link check params params
func (o *LinkCheckParamsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the link check params params
func (o *LinkCheckParamsParams) WithID(id string) *LinkCheckParamsParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the link check params params
func (o *LinkCheckParamsParams) SetID(id string) {
	o.ID = id
}

// WithFollow adds the follow to the link check params params
func (o *LinkCheckParamsParams) WithFollow(follow *string) *LinkCheckParamsParams {
	o.SetFollow(follow)
	return o
}

// SetFollow adds the follow to the link check params params
func (o *LinkCheckParamsParams) SetFollow(follow *string) {
	o.Follow = follow
}

// WriteToRequest writes these params to a swagger request
func (o *LinkCheckParamsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param ID
	if err := r.SetPathParam("ID", o.ID); err != nil {
		return err
	}

	if o.Follow != nil {

		// query param follow
		var qrFollow string

		if o.Follow != nil {
			qrFollow = *o.Follow
		}
		qFollow := qrFollow
		if qFollow != "" {

			if err := r.SetQueryParam("follow", qFollow); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
