// Code generated by go-swagger; DO NOT EDIT.

package other

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/otakakot/sample-mailpit/pkg/mailpit/models"
)

// LinkCheckParamsReader is a Reader for the LinkCheckParams structure.
type LinkCheckParamsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LinkCheckParamsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewLinkCheckParamsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewLinkCheckParamsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewLinkCheckParamsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/v1/message/{ID}/link-check] LinkCheckParams", response, response.Code())
	}
}

// NewLinkCheckParamsOK creates a LinkCheckParamsOK with default headers values
func NewLinkCheckParamsOK() *LinkCheckParamsOK {
	return &LinkCheckParamsOK{}
}

/*
LinkCheckParamsOK describes a response with status code 200, with default header values.

LinkCheckResponse
*/
type LinkCheckParamsOK struct {
	Payload *models.Response
}

// IsSuccess returns true when this link check params o k response has a 2xx status code
func (o *LinkCheckParamsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this link check params o k response has a 3xx status code
func (o *LinkCheckParamsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this link check params o k response has a 4xx status code
func (o *LinkCheckParamsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this link check params o k response has a 5xx status code
func (o *LinkCheckParamsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this link check params o k response a status code equal to that given
func (o *LinkCheckParamsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the link check params o k response
func (o *LinkCheckParamsOK) Code() int {
	return 200
}

func (o *LinkCheckParamsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/message/{ID}/link-check][%d] linkCheckParamsOK %s", 200, payload)
}

func (o *LinkCheckParamsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/message/{ID}/link-check][%d] linkCheckParamsOK %s", 200, payload)
}

func (o *LinkCheckParamsOK) GetPayload() *models.Response {
	return o.Payload
}

func (o *LinkCheckParamsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Response)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewLinkCheckParamsBadRequest creates a LinkCheckParamsBadRequest with default headers values
func NewLinkCheckParamsBadRequest() *LinkCheckParamsBadRequest {
	return &LinkCheckParamsBadRequest{}
}

/*
	LinkCheckParamsBadRequest describes a response with status code 400, with default header values.

	Server error will return with a 400 status code

with the error message in the body
*/
type LinkCheckParamsBadRequest struct {
	Payload string
}

// IsSuccess returns true when this link check params bad request response has a 2xx status code
func (o *LinkCheckParamsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this link check params bad request response has a 3xx status code
func (o *LinkCheckParamsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this link check params bad request response has a 4xx status code
func (o *LinkCheckParamsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this link check params bad request response has a 5xx status code
func (o *LinkCheckParamsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this link check params bad request response a status code equal to that given
func (o *LinkCheckParamsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the link check params bad request response
func (o *LinkCheckParamsBadRequest) Code() int {
	return 400
}

func (o *LinkCheckParamsBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/message/{ID}/link-check][%d] linkCheckParamsBadRequest %s", 400, payload)
}

func (o *LinkCheckParamsBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/message/{ID}/link-check][%d] linkCheckParamsBadRequest %s", 400, payload)
}

func (o *LinkCheckParamsBadRequest) GetPayload() string {
	return o.Payload
}

func (o *LinkCheckParamsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewLinkCheckParamsNotFound creates a LinkCheckParamsNotFound with default headers values
func NewLinkCheckParamsNotFound() *LinkCheckParamsNotFound {
	return &LinkCheckParamsNotFound{}
}

/*
LinkCheckParamsNotFound describes a response with status code 404, with default header values.

Not found error will return a 404 status code
*/
type LinkCheckParamsNotFound struct {
	Payload string
}

// IsSuccess returns true when this link check params not found response has a 2xx status code
func (o *LinkCheckParamsNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this link check params not found response has a 3xx status code
func (o *LinkCheckParamsNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this link check params not found response has a 4xx status code
func (o *LinkCheckParamsNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this link check params not found response has a 5xx status code
func (o *LinkCheckParamsNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this link check params not found response a status code equal to that given
func (o *LinkCheckParamsNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the link check params not found response
func (o *LinkCheckParamsNotFound) Code() int {
	return 404
}

func (o *LinkCheckParamsNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/message/{ID}/link-check][%d] linkCheckParamsNotFound %s", 404, payload)
}

func (o *LinkCheckParamsNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/message/{ID}/link-check][%d] linkCheckParamsNotFound %s", 404, payload)
}

func (o *LinkCheckParamsNotFound) GetPayload() string {
	return o.Payload
}

func (o *LinkCheckParamsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
