// Code generated by go-swagger; DO NOT EDIT.

package other

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new other API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new other API client with basic auth credentials.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new other API client with a bearer token for authentication.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

/*
Client for other API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	HTMLCheckParams(params *HTMLCheckParamsParams, opts ...ClientOption) (*HTMLCheckParamsOK, error)

	LinkCheckParams(params *LinkCheckParamsParams, opts ...ClientOption) (*LinkCheckParamsOK, error)

	SpamAssassinCheckParams(params *SpamAssassinCheckParamsParams, opts ...ClientOption) (*SpamAssassinCheckParamsOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
	HTMLCheckParams HTMLs check

	Returns the summary of the message HTML checker.

The ID can be set to `latest` to return the latest message.
*/
func (a *Client) HTMLCheckParams(params *HTMLCheckParamsParams, opts ...ClientOption) (*HTMLCheckParamsOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewHTMLCheckParamsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "HTMLCheckParams",
		Method:             "GET",
		PathPattern:        "/api/v1/message/{ID}/html-check",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &HTMLCheckParamsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*HTMLCheckParamsOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for HTMLCheckParams: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
	LinkCheckParams links check

	Returns the summary of the message Link checker.

The ID can be set to `latest` to return the latest message.
*/
func (a *Client) LinkCheckParams(params *LinkCheckParamsParams, opts ...ClientOption) (*LinkCheckParamsOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewLinkCheckParamsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "LinkCheckParams",
		Method:             "GET",
		PathPattern:        "/api/v1/message/{ID}/link-check",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &LinkCheckParamsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*LinkCheckParamsOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for LinkCheckParams: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
	SpamAssassinCheckParams spams assassin check

	Returns the SpamAssassin summary (if enabled) of the message.

The ID can be set to `latest` to return the latest message.
*/
func (a *Client) SpamAssassinCheckParams(params *SpamAssassinCheckParamsParams, opts ...ClientOption) (*SpamAssassinCheckParamsOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewSpamAssassinCheckParamsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "SpamAssassinCheckParams",
		Method:             "GET",
		PathPattern:        "/api/v1/message/{ID}/sa-check",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &SpamAssassinCheckParamsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*SpamAssassinCheckParamsOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for SpamAssassinCheckParams: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
