// Code generated by go-swagger; DO NOT EDIT.

package other

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/otakakot/sample-mailpit/pkg/mailpit/models"
)

// SpamAssassinCheckParamsReader is a Reader for the SpamAssassinCheckParams structure.
type SpamAssassinCheckParamsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SpamAssassinCheckParamsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewSpamAssassinCheckParamsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewSpamAssassinCheckParamsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewSpamAssassinCheckParamsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/v1/message/{ID}/sa-check] SpamAssassinCheckParams", response, response.Code())
	}
}

// NewSpamAssassinCheckParamsOK creates a SpamAssassinCheckParamsOK with default headers values
func NewSpamAssassinCheckParamsOK() *SpamAssassinCheckParamsOK {
	return &SpamAssassinCheckParamsOK{}
}

/*
SpamAssassinCheckParamsOK describes a response with status code 200, with default header values.

SpamAssassinResponse
*/
type SpamAssassinCheckParamsOK struct {
	Payload *models.Result
}

// IsSuccess returns true when this spam assassin check params o k response has a 2xx status code
func (o *SpamAssassinCheckParamsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this spam assassin check params o k response has a 3xx status code
func (o *SpamAssassinCheckParamsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this spam assassin check params o k response has a 4xx status code
func (o *SpamAssassinCheckParamsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this spam assassin check params o k response has a 5xx status code
func (o *SpamAssassinCheckParamsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this spam assassin check params o k response a status code equal to that given
func (o *SpamAssassinCheckParamsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the spam assassin check params o k response
func (o *SpamAssassinCheckParamsOK) Code() int {
	return 200
}

func (o *SpamAssassinCheckParamsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/message/{ID}/sa-check][%d] spamAssassinCheckParamsOK %s", 200, payload)
}

func (o *SpamAssassinCheckParamsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/message/{ID}/sa-check][%d] spamAssassinCheckParamsOK %s", 200, payload)
}

func (o *SpamAssassinCheckParamsOK) GetPayload() *models.Result {
	return o.Payload
}

func (o *SpamAssassinCheckParamsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Result)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewSpamAssassinCheckParamsBadRequest creates a SpamAssassinCheckParamsBadRequest with default headers values
func NewSpamAssassinCheckParamsBadRequest() *SpamAssassinCheckParamsBadRequest {
	return &SpamAssassinCheckParamsBadRequest{}
}

/*
	SpamAssassinCheckParamsBadRequest describes a response with status code 400, with default header values.

	Server error will return with a 400 status code

with the error message in the body
*/
type SpamAssassinCheckParamsBadRequest struct {
	Payload string
}

// IsSuccess returns true when this spam assassin check params bad request response has a 2xx status code
func (o *SpamAssassinCheckParamsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this spam assassin check params bad request response has a 3xx status code
func (o *SpamAssassinCheckParamsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this spam assassin check params bad request response has a 4xx status code
func (o *SpamAssassinCheckParamsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this spam assassin check params bad request response has a 5xx status code
func (o *SpamAssassinCheckParamsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this spam assassin check params bad request response a status code equal to that given
func (o *SpamAssassinCheckParamsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the spam assassin check params bad request response
func (o *SpamAssassinCheckParamsBadRequest) Code() int {
	return 400
}

func (o *SpamAssassinCheckParamsBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/message/{ID}/sa-check][%d] spamAssassinCheckParamsBadRequest %s", 400, payload)
}

func (o *SpamAssassinCheckParamsBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/message/{ID}/sa-check][%d] spamAssassinCheckParamsBadRequest %s", 400, payload)
}

func (o *SpamAssassinCheckParamsBadRequest) GetPayload() string {
	return o.Payload
}

func (o *SpamAssassinCheckParamsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewSpamAssassinCheckParamsNotFound creates a SpamAssassinCheckParamsNotFound with default headers values
func NewSpamAssassinCheckParamsNotFound() *SpamAssassinCheckParamsNotFound {
	return &SpamAssassinCheckParamsNotFound{}
}

/*
SpamAssassinCheckParamsNotFound describes a response with status code 404, with default header values.

Not found error will return a 404 status code
*/
type SpamAssassinCheckParamsNotFound struct {
	Payload string
}

// IsSuccess returns true when this spam assassin check params not found response has a 2xx status code
func (o *SpamAssassinCheckParamsNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this spam assassin check params not found response has a 3xx status code
func (o *SpamAssassinCheckParamsNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this spam assassin check params not found response has a 4xx status code
func (o *SpamAssassinCheckParamsNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this spam assassin check params not found response has a 5xx status code
func (o *SpamAssassinCheckParamsNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this spam assassin check params not found response a status code equal to that given
func (o *SpamAssassinCheckParamsNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the spam assassin check params not found response
func (o *SpamAssassinCheckParamsNotFound) Code() int {
	return 404
}

func (o *SpamAssassinCheckParamsNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/message/{ID}/sa-check][%d] spamAssassinCheckParamsNotFound %s", 404, payload)
}

func (o *SpamAssassinCheckParamsNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/message/{ID}/sa-check][%d] spamAssassinCheckParamsNotFound %s", 404, payload)
}

func (o *SpamAssassinCheckParamsNotFound) GetPayload() string {
	return o.Payload
}

func (o *SpamAssassinCheckParamsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
