// Code generated by go-swagger; DO NOT EDIT.

package other

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewSpamAssassinCheckParamsParams creates a new SpamAssassinCheckParamsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSpamAssassinCheckParamsParams() *SpamAssassinCheckParamsParams {
	return &SpamAssassinCheckParamsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSpamAssassinCheckParamsParamsWithTimeout creates a new SpamAssassinCheckParamsParams object
// with the ability to set a timeout on a request.
func NewSpamAssassinCheckParamsParamsWithTimeout(timeout time.Duration) *SpamAssassinCheckParamsParams {
	return &SpamAssassinCheckParamsParams{
		timeout: timeout,
	}
}

// NewSpamAssassinCheckParamsParamsWithContext creates a new SpamAssassinCheckParamsParams object
// with the ability to set a context for a request.
func NewSpamAssassinCheckParamsParamsWithContext(ctx context.Context) *SpamAssassinCheckParamsParams {
	return &SpamAssassinCheckParamsParams{
		Context: ctx,
	}
}

// NewSpamAssassinCheckParamsParamsWithHTTPClient creates a new SpamAssassinCheckParamsParams object
// with the ability to set a custom HTTPClient for a request.
func NewSpamAssassinCheckParamsParamsWithHTTPClient(client *http.Client) *SpamAssassinCheckParamsParams {
	return &SpamAssassinCheckParamsParams{
		HTTPClient: client,
	}
}

/*
SpamAssassinCheckParamsParams contains all the parameters to send to the API endpoint

	for the spam assassin check params operation.

	Typically these are written to a http.Request.
*/
type SpamAssassinCheckParamsParams struct {

	/* ID.

	   Message database ID or "latest"
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the spam assassin check params params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SpamAssassinCheckParamsParams) WithDefaults() *SpamAssassinCheckParamsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the spam assassin check params params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SpamAssassinCheckParamsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the spam assassin check params params
func (o *SpamAssassinCheckParamsParams) WithTimeout(timeout time.Duration) *SpamAssassinCheckParamsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the spam assassin check params params
func (o *SpamAssassinCheckParamsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the spam assassin check params params
func (o *SpamAssassinCheckParamsParams) WithContext(ctx context.Context) *SpamAssassinCheckParamsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the spam assassin check params params
func (o *SpamAssassinCheckParamsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the spam assassin check params params
func (o *SpamAssassinCheckParamsParams) WithHTTPClient(client *http.Client) *SpamAssassinCheckParamsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the spam assassin check params params
func (o *SpamAssassinCheckParamsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the spam assassin check params params
func (o *SpamAssassinCheckParamsParams) WithID(id string) *SpamAssassinCheckParamsParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the spam assassin check params params
func (o *SpamAssassinCheckParamsParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *SpamAssassinCheckParamsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param ID
	if err := r.SetPathParam("ID", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
