// Code generated by go-swagger; DO NOT EDIT.

package messages

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteMessagesParamsParams creates a new DeleteMessagesParamsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteMessagesParamsParams() *DeleteMessagesParamsParams {
	return &DeleteMessagesParamsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteMessagesParamsParamsWithTimeout creates a new DeleteMessagesParamsParams object
// with the ability to set a timeout on a request.
func NewDeleteMessagesParamsParamsWithTimeout(timeout time.Duration) *DeleteMessagesParamsParams {
	return &DeleteMessagesParamsParams{
		timeout: timeout,
	}
}

// NewDeleteMessagesParamsParamsWithContext creates a new DeleteMessagesParamsParams object
// with the ability to set a context for a request.
func NewDeleteMessagesParamsParamsWithContext(ctx context.Context) *DeleteMessagesParamsParams {
	return &DeleteMessagesParamsParams{
		Context: ctx,
	}
}

// NewDeleteMessagesParamsParamsWithHTTPClient creates a new DeleteMessagesParamsParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteMessagesParamsParamsWithHTTPClient(client *http.Client) *DeleteMessagesParamsParams {
	return &DeleteMessagesParamsParams{
		HTTPClient: client,
	}
}

/*
DeleteMessagesParamsParams contains all the parameters to send to the API endpoint

	for the delete messages params operation.

	Typically these are written to a http.Request.
*/
type DeleteMessagesParamsParams struct {

	/* Body.

	   Delete request
	*/
	Body DeleteMessagesParamsBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete messages params params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteMessagesParamsParams) WithDefaults() *DeleteMessagesParamsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete messages params params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteMessagesParamsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete messages params params
func (o *DeleteMessagesParamsParams) WithTimeout(timeout time.Duration) *DeleteMessagesParamsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete messages params params
func (o *DeleteMessagesParamsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete messages params params
func (o *DeleteMessagesParamsParams) WithContext(ctx context.Context) *DeleteMessagesParamsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete messages params params
func (o *DeleteMessagesParamsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete messages params params
func (o *DeleteMessagesParamsParams) WithHTTPClient(client *http.Client) *DeleteMessagesParamsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete messages params params
func (o *DeleteMessagesParamsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the delete messages params params
func (o *DeleteMessagesParamsParams) WithBody(body DeleteMessagesParamsBody) *DeleteMessagesParamsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the delete messages params params
func (o *DeleteMessagesParamsParams) SetBody(body DeleteMessagesParamsBody) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteMessagesParamsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
