// Code generated by go-swagger; DO NOT EDIT.

package messages

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteSearchParamsReader is a Reader for the DeleteSearchParams structure.
type DeleteSearchParamsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteSearchParamsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteSearchParamsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteSearchParamsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /api/v1/search] DeleteSearchParams", response, response.Code())
	}
}

// NewDeleteSearchParamsOK creates a DeleteSearchParamsOK with default headers values
func NewDeleteSearchParamsOK() *DeleteSearchParamsOK {
	return &DeleteSearchParamsOK{}
}

/*
DeleteSearchParamsOK describes a response with status code 200, with default header values.

Plain text "ok" response
*/
type DeleteSearchParamsOK struct {
	Payload string
}

// IsSuccess returns true when this delete search params o k response has a 2xx status code
func (o *DeleteSearchParamsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete search params o k response has a 3xx status code
func (o *DeleteSearchParamsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete search params o k response has a 4xx status code
func (o *DeleteSearchParamsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete search params o k response has a 5xx status code
func (o *DeleteSearchParamsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete search params o k response a status code equal to that given
func (o *DeleteSearchParamsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the delete search params o k response
func (o *DeleteSearchParamsOK) Code() int {
	return 200
}

func (o *DeleteSearchParamsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/v1/search][%d] deleteSearchParamsOK %s", 200, payload)
}

func (o *DeleteSearchParamsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/v1/search][%d] deleteSearchParamsOK %s", 200, payload)
}

func (o *DeleteSearchParamsOK) GetPayload() string {
	return o.Payload
}

func (o *DeleteSearchParamsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDeleteSearchParamsBadRequest creates a DeleteSearchParamsBadRequest with default headers values
func NewDeleteSearchParamsBadRequest() *DeleteSearchParamsBadRequest {
	return &DeleteSearchParamsBadRequest{}
}

/*
	DeleteSearchParamsBadRequest describes a response with status code 400, with default header values.

	Server error will return with a 400 status code

with the error message in the body
*/
type DeleteSearchParamsBadRequest struct {
	Payload string
}

// IsSuccess returns true when this delete search params bad request response has a 2xx status code
func (o *DeleteSearchParamsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete search params bad request response has a 3xx status code
func (o *DeleteSearchParamsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete search params bad request response has a 4xx status code
func (o *DeleteSearchParamsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete search params bad request response has a 5xx status code
func (o *DeleteSearchParamsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this delete search params bad request response a status code equal to that given
func (o *DeleteSearchParamsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the delete search params bad request response
func (o *DeleteSearchParamsBadRequest) Code() int {
	return 400
}

func (o *DeleteSearchParamsBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/v1/search][%d] deleteSearchParamsBadRequest %s", 400, payload)
}

func (o *DeleteSearchParamsBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/v1/search][%d] deleteSearchParamsBadRequest %s", 400, payload)
}

func (o *DeleteSearchParamsBadRequest) GetPayload() string {
	return o.Payload
}

func (o *DeleteSearchParamsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
