// Code generated by go-swagger; DO NOT EDIT.

package messages

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DeleteMessagesParamsReader is a Reader for the DeleteMessagesParams structure.
type DeleteMessagesParamsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteMessagesParamsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteMessagesParamsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteMessagesParamsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /api/v1/messages] DeleteMessagesParams", response, response.Code())
	}
}

// NewDeleteMessagesParamsOK creates a DeleteMessagesParamsOK with default headers values
func NewDeleteMessagesParamsOK() *DeleteMessagesParamsOK {
	return &DeleteMessagesParamsOK{}
}

/*
DeleteMessagesParamsOK describes a response with status code 200, with default header values.

Plain text "ok" response
*/
type DeleteMessagesParamsOK struct {
	Payload string
}

// IsSuccess returns true when this delete messages params o k response has a 2xx status code
func (o *DeleteMessagesParamsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete messages params o k response has a 3xx status code
func (o *DeleteMessagesParamsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete messages params o k response has a 4xx status code
func (o *DeleteMessagesParamsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete messages params o k response has a 5xx status code
func (o *DeleteMessagesParamsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete messages params o k response a status code equal to that given
func (o *DeleteMessagesParamsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the delete messages params o k response
func (o *DeleteMessagesParamsOK) Code() int {
	return 200
}

func (o *DeleteMessagesParamsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/v1/messages][%d] deleteMessagesParamsOK %s", 200, payload)
}

func (o *DeleteMessagesParamsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/v1/messages][%d] deleteMessagesParamsOK %s", 200, payload)
}

func (o *DeleteMessagesParamsOK) GetPayload() string {
	return o.Payload
}

func (o *DeleteMessagesParamsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDeleteMessagesParamsBadRequest creates a DeleteMessagesParamsBadRequest with default headers values
func NewDeleteMessagesParamsBadRequest() *DeleteMessagesParamsBadRequest {
	return &DeleteMessagesParamsBadRequest{}
}

/*
	DeleteMessagesParamsBadRequest describes a response with status code 400, with default header values.

	Server error will return with a 400 status code

with the error message in the body
*/
type DeleteMessagesParamsBadRequest struct {
	Payload string
}

// IsSuccess returns true when this delete messages params bad request response has a 2xx status code
func (o *DeleteMessagesParamsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete messages params bad request response has a 3xx status code
func (o *DeleteMessagesParamsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete messages params bad request response has a 4xx status code
func (o *DeleteMessagesParamsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete messages params bad request response has a 5xx status code
func (o *DeleteMessagesParamsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this delete messages params bad request response a status code equal to that given
func (o *DeleteMessagesParamsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the delete messages params bad request response
func (o *DeleteMessagesParamsBadRequest) Code() int {
	return 400
}

func (o *DeleteMessagesParamsBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/v1/messages][%d] deleteMessagesParamsBadRequest %s", 400, payload)
}

func (o *DeleteMessagesParamsBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/v1/messages][%d] deleteMessagesParamsBadRequest %s", 400, payload)
}

func (o *DeleteMessagesParamsBadRequest) GetPayload() string {
	return o.Payload
}

func (o *DeleteMessagesParamsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

/*
DeleteMessagesParamsBody delete messages params body
swagger:model DeleteMessagesParamsBody
*/
type DeleteMessagesParamsBody struct {

	// Array of message database IDs
	// Example: ["4oRBnPtCXgAqZniRhzLNmS","hXayS6wnCgNnt6aFTvmOF6"]
	IDs []string `json:"IDs"`
}

// Validate validates this delete messages params body
func (o *DeleteMessagesParamsBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this delete messages params body based on context it is used
func (o *DeleteMessagesParamsBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DeleteMessagesParamsBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteMessagesParamsBody) UnmarshalBinary(b []byte) error {
	var res DeleteMessagesParamsBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
