// Code generated by go-swagger; DO NOT EDIT.

package messages

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteSearchParamsParams creates a new DeleteSearchParamsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteSearchParamsParams() *DeleteSearchParamsParams {
	return &DeleteSearchParamsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteSearchParamsParamsWithTimeout creates a new DeleteSearchParamsParams object
// with the ability to set a timeout on a request.
func NewDeleteSearchParamsParamsWithTimeout(timeout time.Duration) *DeleteSearchParamsParams {
	return &DeleteSearchParamsParams{
		timeout: timeout,
	}
}

// NewDeleteSearchParamsParamsWithContext creates a new DeleteSearchParamsParams object
// with the ability to set a context for a request.
func NewDeleteSearchParamsParamsWithContext(ctx context.Context) *DeleteSearchParamsParams {
	return &DeleteSearchParamsParams{
		Context: ctx,
	}
}

// NewDeleteSearchParamsParamsWithHTTPClient creates a new DeleteSearchParamsParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteSearchParamsParamsWithHTTPClient(client *http.Client) *DeleteSearchParamsParams {
	return &DeleteSearchParamsParams{
		HTTPClient: client,
	}
}

/*
DeleteSearchParamsParams contains all the parameters to send to the API endpoint

	for the delete search params operation.

	Typically these are written to a http.Request.
*/
type DeleteSearchParamsParams struct {

	/* Query.

	   Search query
	*/
	Query string

	/* Tz.

	   [Timezone identifier](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones) used only for `before:` & `after:` searches (eg: "Pacific/Auckland").
	*/
	TZ *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete search params params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteSearchParamsParams) WithDefaults() *DeleteSearchParamsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete search params params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteSearchParamsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete search params params
func (o *DeleteSearchParamsParams) WithTimeout(timeout time.Duration) *DeleteSearchParamsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete search params params
func (o *DeleteSearchParamsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete search params params
func (o *DeleteSearchParamsParams) WithContext(ctx context.Context) *DeleteSearchParamsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete search params params
func (o *DeleteSearchParamsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete search params params
func (o *DeleteSearchParamsParams) WithHTTPClient(client *http.Client) *DeleteSearchParamsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete search params params
func (o *DeleteSearchParamsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithQuery adds the query to the delete search params params
func (o *DeleteSearchParamsParams) WithQuery(query string) *DeleteSearchParamsParams {
	o.SetQuery(query)
	return o
}

// SetQuery adds the query to the delete search params params
func (o *DeleteSearchParamsParams) SetQuery(query string) {
	o.Query = query
}

// WithTZ adds the tz to the delete search params params
func (o *DeleteSearchParamsParams) WithTZ(tz *string) *DeleteSearchParamsParams {
	o.SetTZ(tz)
	return o
}

// SetTZ adds the tz to the delete search params params
func (o *DeleteSearchParamsParams) SetTZ(tz *string) {
	o.TZ = tz
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteSearchParamsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param query
	qrQuery := o.Query
	qQuery := qrQuery
	if qQuery != "" {

		if err := r.SetQueryParam("query", qQuery); err != nil {
			return err
		}
	}

	if o.TZ != nil {

		// query param tz
		var qrTz string

		if o.TZ != nil {
			qrTz = *o.TZ
		}
		qTz := qrTz
		if qTz != "" {

			if err := r.SetQueryParam("tz", qTz); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
