// Code generated by go-swagger; DO NOT EDIT.

package messages

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/otakakot/sample-mailpit/pkg/mailpit/models"
)

// GetMessagesParamsReader is a Reader for the GetMessagesParams structure.
type GetMessagesParamsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetMessagesParamsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetMessagesParamsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetMessagesParamsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/v1/messages] GetMessagesParams", response, response.Code())
	}
}

// NewGetMessagesParamsOK creates a GetMessagesParamsOK with default headers values
func NewGetMessagesParamsOK() *GetMessagesParamsOK {
	return &GetMessagesParamsOK{}
}

/*
GetMessagesParamsOK describes a response with status code 200, with default header values.

Summary of messages
*/
type GetMessagesParamsOK struct {
	Payload *models.MessagesSummary
}

// IsSuccess returns true when this get messages params o k response has a 2xx status code
func (o *GetMessagesParamsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get messages params o k response has a 3xx status code
func (o *GetMessagesParamsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get messages params o k response has a 4xx status code
func (o *GetMessagesParamsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get messages params o k response has a 5xx status code
func (o *GetMessagesParamsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get messages params o k response a status code equal to that given
func (o *GetMessagesParamsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get messages params o k response
func (o *GetMessagesParamsOK) Code() int {
	return 200
}

func (o *GetMessagesParamsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/messages][%d] getMessagesParamsOK %s", 200, payload)
}

func (o *GetMessagesParamsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/messages][%d] getMessagesParamsOK %s", 200, payload)
}

func (o *GetMessagesParamsOK) GetPayload() *models.MessagesSummary {
	return o.Payload
}

func (o *GetMessagesParamsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MessagesSummary)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetMessagesParamsBadRequest creates a GetMessagesParamsBadRequest with default headers values
func NewGetMessagesParamsBadRequest() *GetMessagesParamsBadRequest {
	return &GetMessagesParamsBadRequest{}
}

/*
	GetMessagesParamsBadRequest describes a response with status code 400, with default header values.

	Server error will return with a 400 status code

with the error message in the body
*/
type GetMessagesParamsBadRequest struct {
	Payload string
}

// IsSuccess returns true when this get messages params bad request response has a 2xx status code
func (o *GetMessagesParamsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get messages params bad request response has a 3xx status code
func (o *GetMessagesParamsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get messages params bad request response has a 4xx status code
func (o *GetMessagesParamsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get messages params bad request response has a 5xx status code
func (o *GetMessagesParamsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get messages params bad request response a status code equal to that given
func (o *GetMessagesParamsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get messages params bad request response
func (o *GetMessagesParamsBadRequest) Code() int {
	return 400
}

func (o *GetMessagesParamsBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/messages][%d] getMessagesParamsBadRequest %s", 400, payload)
}

func (o *GetMessagesParamsBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/messages][%d] getMessagesParamsBadRequest %s", 400, payload)
}

func (o *GetMessagesParamsBadRequest) GetPayload() string {
	return o.Payload
}

func (o *GetMessagesParamsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
