// Code generated by go-swagger; DO NOT EDIT.

package messages

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new messages API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new messages API client with basic auth credentials.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new messages API client with a bearer token for authentication.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

/*
Client for messages API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// This client is generated with a few options you might find useful for your swagger spec.
//
// Feel free to add you own set of options.

// WithAccept allows the client to force the Accept header
// to negotiate a specific Producer from the server.
//
// You may use this option to set arbitrary extensions to your MIME media type.
func WithAccept(mime string) ClientOption {
	return func(r *runtime.ClientOperation) {
		r.ProducesMediaTypes = []string{mime}
	}
}

// WithAcceptApplicationJSON sets the Accept header to "application/json".
func WithAcceptApplicationJSON(r *runtime.ClientOperation) {
	r.ProducesMediaTypes = []string{"application/json"}
}

// WithAcceptTextPlain sets the Accept header to "text/plain".
func WithAcceptTextPlain(r *runtime.ClientOperation) {
	r.ProducesMediaTypes = []string{"text/plain"}
}

// ClientService is the interface for Client methods
type ClientService interface {
	DeleteMessagesParams(params *DeleteMessagesParamsParams, opts ...ClientOption) (*DeleteMessagesParamsOK, error)

	DeleteSearchParams(params *DeleteSearchParamsParams, opts ...ClientOption) (*DeleteSearchParamsOK, error)

	GetMessagesParams(params *GetMessagesParamsParams, opts ...ClientOption) (*GetMessagesParamsOK, error)

	SearchParams(params *SearchParamsParams, opts ...ClientOption) (*SearchParamsOK, error)

	SetReadStatusParams(params *SetReadStatusParamsParams, opts ...ClientOption) (*SetReadStatusParamsOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
DeleteMessagesParams deletes messages

Delete individual or all messages. If no IDs are provided then all messages are deleted.
*/
func (a *Client) DeleteMessagesParams(params *DeleteMessagesParamsParams, opts ...ClientOption) (*DeleteMessagesParamsOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewDeleteMessagesParamsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "DeleteMessagesParams",
		Method:             "DELETE",
		PathPattern:        "/api/v1/messages",
		ProducesMediaTypes: []string{"text/plain"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &DeleteMessagesParamsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*DeleteMessagesParamsOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for DeleteMessagesParams: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
DeleteSearchParams deletes messages by search

Delete all messages matching [a search](https://mailpit.axllent.org/docs/usage/search-filters/).
*/
func (a *Client) DeleteSearchParams(params *DeleteSearchParamsParams, opts ...ClientOption) (*DeleteSearchParamsOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewDeleteSearchParamsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "DeleteSearchParams",
		Method:             "DELETE",
		PathPattern:        "/api/v1/search",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &DeleteSearchParamsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*DeleteSearchParamsOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for DeleteSearchParams: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetMessagesParams lists messages

Returns messages from the mailbox ordered from newest to oldest.
*/
func (a *Client) GetMessagesParams(params *GetMessagesParamsParams, opts ...ClientOption) (*GetMessagesParamsOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetMessagesParamsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetMessagesParams",
		Method:             "GET",
		PathPattern:        "/api/v1/messages",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetMessagesParamsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetMessagesParamsOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetMessagesParams: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
SearchParams searches messages

Returns messages matching [a search](https://mailpit.axllent.org/docs/usage/search-filters/), sorted by received date (descending).
*/
func (a *Client) SearchParams(params *SearchParamsParams, opts ...ClientOption) (*SearchParamsOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewSearchParamsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "SearchParams",
		Method:             "GET",
		PathPattern:        "/api/v1/search",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &SearchParamsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*SearchParamsOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for SearchParams: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
	SetReadStatusParams sets read status

	You can optionally provide an array of IDs or a search string.

If neither IDs nor search is provided then all mailbox messages are updated.
*/
func (a *Client) SetReadStatusParams(params *SetReadStatusParamsParams, opts ...ClientOption) (*SetReadStatusParamsOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewSetReadStatusParamsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "SetReadStatusParams",
		Method:             "PUT",
		PathPattern:        "/api/v1/messages",
		ProducesMediaTypes: []string{"text/plain"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &SetReadStatusParamsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*SetReadStatusParamsOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for SetReadStatusParams: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
