// Code generated by go-swagger; DO NOT EDIT.

package messages

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewSearchParamsParams creates a new SearchParamsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSearchParamsParams() *SearchParamsParams {
	return &SearchParamsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSearchParamsParamsWithTimeout creates a new SearchParamsParams object
// with the ability to set a timeout on a request.
func NewSearchParamsParamsWithTimeout(timeout time.Duration) *SearchParamsParams {
	return &SearchParamsParams{
		timeout: timeout,
	}
}

// NewSearchParamsParamsWithContext creates a new SearchParamsParams object
// with the ability to set a context for a request.
func NewSearchParamsParamsWithContext(ctx context.Context) *SearchParamsParams {
	return &SearchParamsParams{
		Context: ctx,
	}
}

// NewSearchParamsParamsWithHTTPClient creates a new SearchParamsParams object
// with the ability to set a custom HTTPClient for a request.
func NewSearchParamsParamsWithHTTPClient(client *http.Client) *SearchParamsParams {
	return &SearchParamsParams{
		HTTPClient: client,
	}
}

/*
SearchParamsParams contains all the parameters to send to the API endpoint

	for the search params operation.

	Typically these are written to a http.Request.
*/
type SearchParamsParams struct {

	/* Limit.

	   Limit results

	   Default: "50"
	*/
	Limit *string

	/* Query.

	   Search query
	*/
	Query string

	/* Start.

	   Pagination offset

	   Default: "0"
	*/
	Start *string

	/* Tz.

	   Optional [timezone identifier](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones) used only for `before:` & `after:` searches (eg: "Pacific/Auckland").
	*/
	TZ *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the search params params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SearchParamsParams) WithDefaults() *SearchParamsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the search params params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SearchParamsParams) SetDefaults() {
	var (
		limitDefault = string("50")

		startDefault = string("0")
	)

	val := SearchParamsParams{
		Limit: &limitDefault,
		Start: &startDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the search params params
func (o *SearchParamsParams) WithTimeout(timeout time.Duration) *SearchParamsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the search params params
func (o *SearchParamsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the search params params
func (o *SearchParamsParams) WithContext(ctx context.Context) *SearchParamsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the search params params
func (o *SearchParamsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the search params params
func (o *SearchParamsParams) WithHTTPClient(client *http.Client) *SearchParamsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the search params params
func (o *SearchParamsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLimit adds the limit to the search params params
func (o *SearchParamsParams) WithLimit(limit *string) *SearchParamsParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the search params params
func (o *SearchParamsParams) SetLimit(limit *string) {
	o.Limit = limit
}

// WithQuery adds the query to the search params params
func (o *SearchParamsParams) WithQuery(query string) *SearchParamsParams {
	o.SetQuery(query)
	return o
}

// SetQuery adds the query to the search params params
func (o *SearchParamsParams) SetQuery(query string) {
	o.Query = query
}

// WithStart adds the start to the search params params
func (o *SearchParamsParams) WithStart(start *string) *SearchParamsParams {
	o.SetStart(start)
	return o
}

// SetStart adds the start to the search params params
func (o *SearchParamsParams) SetStart(start *string) {
	o.Start = start
}

// WithTZ adds the tz to the search params params
func (o *SearchParamsParams) WithTZ(tz *string) *SearchParamsParams {
	o.SetTZ(tz)
	return o
}

// SetTZ adds the tz to the search params params
func (o *SearchParamsParams) SetTZ(tz *string) {
	o.TZ = tz
}

// WriteToRequest writes these params to a swagger request
func (o *SearchParamsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Limit != nil {

		// query param limit
		var qrLimit string

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := qrLimit
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	// query param query
	qrQuery := o.Query
	qQuery := qrQuery
	if qQuery != "" {

		if err := r.SetQueryParam("query", qQuery); err != nil {
			return err
		}
	}

	if o.Start != nil {

		// query param start
		var qrStart string

		if o.Start != nil {
			qrStart = *o.Start
		}
		qStart := qrStart
		if qStart != "" {

			if err := r.SetQueryParam("start", qStart); err != nil {
				return err
			}
		}
	}

	if o.TZ != nil {

		// query param tz
		var qrTz string

		if o.TZ != nil {
			qrTz = *o.TZ
		}
		qTz := qrTz
		if qTz != "" {

			if err := r.SetQueryParam("tz", qTz); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
