// Code generated by go-swagger; DO NOT EDIT.

package messages

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/otakakot/sample-mailpit/pkg/mailpit/models"
)

// SearchParamsReader is a Reader for the SearchParams structure.
type SearchParamsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SearchParamsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewSearchParamsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewSearchParamsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/v1/search] SearchParams", response, response.Code())
	}
}

// NewSearchParamsOK creates a SearchParamsOK with default headers values
func NewSearchParamsOK() *SearchParamsOK {
	return &SearchParamsOK{}
}

/*
SearchParamsOK describes a response with status code 200, with default header values.

Summary of messages
*/
type SearchParamsOK struct {
	Payload *models.MessagesSummary
}

// IsSuccess returns true when this search params o k response has a 2xx status code
func (o *SearchParamsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this search params o k response has a 3xx status code
func (o *SearchParamsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this search params o k response has a 4xx status code
func (o *SearchParamsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this search params o k response has a 5xx status code
func (o *SearchParamsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this search params o k response a status code equal to that given
func (o *SearchParamsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the search params o k response
func (o *SearchParamsOK) Code() int {
	return 200
}

func (o *SearchParamsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/search][%d] searchParamsOK %s", 200, payload)
}

func (o *SearchParamsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/search][%d] searchParamsOK %s", 200, payload)
}

func (o *SearchParamsOK) GetPayload() *models.MessagesSummary {
	return o.Payload
}

func (o *SearchParamsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MessagesSummary)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewSearchParamsBadRequest creates a SearchParamsBadRequest with default headers values
func NewSearchParamsBadRequest() *SearchParamsBadRequest {
	return &SearchParamsBadRequest{}
}

/*
	SearchParamsBadRequest describes a response with status code 400, with default header values.

	Server error will return with a 400 status code

with the error message in the body
*/
type SearchParamsBadRequest struct {
	Payload string
}

// IsSuccess returns true when this search params bad request response has a 2xx status code
func (o *SearchParamsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this search params bad request response has a 3xx status code
func (o *SearchParamsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this search params bad request response has a 4xx status code
func (o *SearchParamsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this search params bad request response has a 5xx status code
func (o *SearchParamsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this search params bad request response a status code equal to that given
func (o *SearchParamsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the search params bad request response
func (o *SearchParamsBadRequest) Code() int {
	return 400
}

func (o *SearchParamsBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/search][%d] searchParamsBadRequest %s", 400, payload)
}

func (o *SearchParamsBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/search][%d] searchParamsBadRequest %s", 400, payload)
}

func (o *SearchParamsBadRequest) GetPayload() string {
	return o.Payload
}

func (o *SearchParamsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
