// Code generated by go-swagger; DO NOT EDIT.

package messages

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SetReadStatusParamsReader is a Reader for the SetReadStatusParams structure.
type SetReadStatusParamsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SetReadStatusParamsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewSetReadStatusParamsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewSetReadStatusParamsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[PUT /api/v1/messages] SetReadStatusParams", response, response.Code())
	}
}

// NewSetReadStatusParamsOK creates a SetReadStatusParamsOK with default headers values
func NewSetReadStatusParamsOK() *SetReadStatusParamsOK {
	return &SetReadStatusParamsOK{}
}

/*
SetReadStatusParamsOK describes a response with status code 200, with default header values.

Plain text "ok" response
*/
type SetReadStatusParamsOK struct {
	Payload string
}

// IsSuccess returns true when this set read status params o k response has a 2xx status code
func (o *SetReadStatusParamsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this set read status params o k response has a 3xx status code
func (o *SetReadStatusParamsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this set read status params o k response has a 4xx status code
func (o *SetReadStatusParamsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this set read status params o k response has a 5xx status code
func (o *SetReadStatusParamsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this set read status params o k response a status code equal to that given
func (o *SetReadStatusParamsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the set read status params o k response
func (o *SetReadStatusParamsOK) Code() int {
	return 200
}

func (o *SetReadStatusParamsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/v1/messages][%d] setReadStatusParamsOK %s", 200, payload)
}

func (o *SetReadStatusParamsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/v1/messages][%d] setReadStatusParamsOK %s", 200, payload)
}

func (o *SetReadStatusParamsOK) GetPayload() string {
	return o.Payload
}

func (o *SetReadStatusParamsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewSetReadStatusParamsBadRequest creates a SetReadStatusParamsBadRequest with default headers values
func NewSetReadStatusParamsBadRequest() *SetReadStatusParamsBadRequest {
	return &SetReadStatusParamsBadRequest{}
}

/*
	SetReadStatusParamsBadRequest describes a response with status code 400, with default header values.

	Server error will return with a 400 status code

with the error message in the body
*/
type SetReadStatusParamsBadRequest struct {
	Payload string
}

// IsSuccess returns true when this set read status params bad request response has a 2xx status code
func (o *SetReadStatusParamsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this set read status params bad request response has a 3xx status code
func (o *SetReadStatusParamsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this set read status params bad request response has a 4xx status code
func (o *SetReadStatusParamsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this set read status params bad request response has a 5xx status code
func (o *SetReadStatusParamsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this set read status params bad request response a status code equal to that given
func (o *SetReadStatusParamsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the set read status params bad request response
func (o *SetReadStatusParamsBadRequest) Code() int {
	return 400
}

func (o *SetReadStatusParamsBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/v1/messages][%d] setReadStatusParamsBadRequest %s", 400, payload)
}

func (o *SetReadStatusParamsBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/v1/messages][%d] setReadStatusParamsBadRequest %s", 400, payload)
}

func (o *SetReadStatusParamsBadRequest) GetPayload() string {
	return o.Payload
}

func (o *SetReadStatusParamsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

/*
SetReadStatusParamsBody set read status params body
swagger:model SetReadStatusParamsBody
*/
type SetReadStatusParamsBody struct {

	// Optional array of message database IDs
	// Example: ["4oRBnPtCXgAqZniRhzLNmS","hXayS6wnCgNnt6aFTvmOF6"]
	IDs []string `json:"IDs"`

	// Read status
	// Example: true
	Read *bool `json:"Read,omitempty"`

	// Optional messages matching a search
	// Example: tag:backups
	Search string `json:"Search,omitempty"`
}

// Validate validates this set read status params body
func (o *SetReadStatusParamsBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this set read status params body based on context it is used
func (o *SetReadStatusParamsBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *SetReadStatusParamsBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *SetReadStatusParamsBody) UnmarshalBinary(b []byte) error {
	var res SetReadStatusParamsBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
