// Code generated by go-swagger; DO NOT EDIT.

package messages

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewSetReadStatusParamsParams creates a new SetReadStatusParamsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSetReadStatusParamsParams() *SetReadStatusParamsParams {
	return &SetReadStatusParamsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSetReadStatusParamsParamsWithTimeout creates a new SetReadStatusParamsParams object
// with the ability to set a timeout on a request.
func NewSetReadStatusParamsParamsWithTimeout(timeout time.Duration) *SetReadStatusParamsParams {
	return &SetReadStatusParamsParams{
		timeout: timeout,
	}
}

// NewSetReadStatusParamsParamsWithContext creates a new SetReadStatusParamsParams object
// with the ability to set a context for a request.
func NewSetReadStatusParamsParamsWithContext(ctx context.Context) *SetReadStatusParamsParams {
	return &SetReadStatusParamsParams{
		Context: ctx,
	}
}

// NewSetReadStatusParamsParamsWithHTTPClient creates a new SetReadStatusParamsParams object
// with the ability to set a custom HTTPClient for a request.
func NewSetReadStatusParamsParamsWithHTTPClient(client *http.Client) *SetReadStatusParamsParams {
	return &SetReadStatusParamsParams{
		HTTPClient: client,
	}
}

/*
SetReadStatusParamsParams contains all the parameters to send to the API endpoint

	for the set read status params operation.

	Typically these are written to a http.Request.
*/
type SetReadStatusParamsParams struct {

	// Body.
	Body SetReadStatusParamsBody

	/* Tz.

	   Optional [timezone identifier](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones) used only for `before:` & `after:` searches (eg: "Pacific/Auckland").
	*/
	TZ *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the set read status params params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SetReadStatusParamsParams) WithDefaults() *SetReadStatusParamsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the set read status params params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SetReadStatusParamsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the set read status params params
func (o *SetReadStatusParamsParams) WithTimeout(timeout time.Duration) *SetReadStatusParamsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the set read status params params
func (o *SetReadStatusParamsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the set read status params params
func (o *SetReadStatusParamsParams) WithContext(ctx context.Context) *SetReadStatusParamsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the set read status params params
func (o *SetReadStatusParamsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the set read status params params
func (o *SetReadStatusParamsParams) WithHTTPClient(client *http.Client) *SetReadStatusParamsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the set read status params params
func (o *SetReadStatusParamsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the set read status params params
func (o *SetReadStatusParamsParams) WithBody(body SetReadStatusParamsBody) *SetReadStatusParamsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the set read status params params
func (o *SetReadStatusParamsParams) SetBody(body SetReadStatusParamsBody) {
	o.Body = body
}

// WithTZ adds the tz to the set read status params params
func (o *SetReadStatusParamsParams) WithTZ(tz *string) *SetReadStatusParamsParams {
	o.SetTZ(tz)
	return o
}

// SetTZ adds the tz to the set read status params params
func (o *SetReadStatusParamsParams) SetTZ(tz *string) {
	o.TZ = tz
}

// WriteToRequest writes these params to a swagger request
func (o *SetReadStatusParamsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if o.TZ != nil {

		// query param tz
		var qrTz string

		if o.TZ != nil {
			qrTz = *o.TZ
		}
		qTz := qrTz
		if qTz != "" {

			if err := r.SetQueryParam("tz", qTz); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
