// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/otakakot/sample-mailpit/pkg/mailpit/client/application"
	"github.com/otakakot/sample-mailpit/pkg/mailpit/client/message"
	"github.com/otakakot/sample-mailpit/pkg/mailpit/client/messages"
	"github.com/otakakot/sample-mailpit/pkg/mailpit/client/other"
	"github.com/otakakot/sample-mailpit/pkg/mailpit/client/tags"
	"github.com/otakakot/sample-mailpit/pkg/mailpit/client/testing"
)

// Default mailpit API HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "localhost"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"http", "https"}

// NewHTTPClient creates a new mailpit API HTTP client.
func NewHTTPClient(formats strfmt.Registry) *MailpitAPI {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new mailpit API HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *MailpitAPI {
	// ensure nullable parameters have default
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new mailpit API client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *MailpitAPI {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}

	cli := new(MailpitAPI)
	cli.Transport = transport
	cli.Application = application.New(transport, formats)
	cli.Message = message.New(transport, formats)
	cli.Messages = messages.New(transport, formats)
	cli.Other = other.New(transport, formats)
	cli.Tags = tags.New(transport, formats)
	cli.Testing = testing.New(transport, formats)
	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// MailpitAPI is a client for mailpit API
type MailpitAPI struct {
	Application application.ClientService

	Message message.ClientService

	Messages messages.ClientService

	Other other.ClientService

	Tags tags.ClientService

	Testing testing.ClientService

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *MailpitAPI) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport
	c.Application.SetTransport(transport)
	c.Message.SetTransport(transport)
	c.Messages.SetTransport(transport)
	c.Other.SetTransport(transport)
	c.Tags.SetTransport(transport)
	c.Testing.SetTransport(transport)
}
