// Code generated by go-swagger; DO NOT EDIT.

package application

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewAppInformationParams creates a new AppInformationParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAppInformationParams() *AppInformationParams {
	return &AppInformationParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAppInformationParamsWithTimeout creates a new AppInformationParams object
// with the ability to set a timeout on a request.
func NewAppInformationParamsWithTimeout(timeout time.Duration) *AppInformationParams {
	return &AppInformationParams{
		timeout: timeout,
	}
}

// NewAppInformationParamsWithContext creates a new AppInformationParams object
// with the ability to set a context for a request.
func NewAppInformationParamsWithContext(ctx context.Context) *AppInformationParams {
	return &AppInformationParams{
		Context: ctx,
	}
}

// NewAppInformationParamsWithHTTPClient creates a new AppInformationParams object
// with the ability to set a custom HTTPClient for a request.
func NewAppInformationParamsWithHTTPClient(client *http.Client) *AppInformationParams {
	return &AppInformationParams{
		HTTPClient: client,
	}
}

/*
AppInformationParams contains all the parameters to send to the API endpoint

	for the app information operation.

	Typically these are written to a http.Request.
*/
type AppInformationParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the app information params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AppInformationParams) WithDefaults() *AppInformationParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the app information params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AppInformationParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the app information params
func (o *AppInformationParams) WithTimeout(timeout time.Duration) *AppInformationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the app information params
func (o *AppInformationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the app information params
func (o *AppInformationParams) WithContext(ctx context.Context) *AppInformationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the app information params
func (o *AppInformationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the app information params
func (o *AppInformationParams) WithHTTPClient(client *http.Client) *AppInformationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the app information params
func (o *AppInformationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *AppInformationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
