// Code generated by go-swagger; DO NOT EDIT.

package application

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/otakakot/sample-mailpit/pkg/mailpit/models"
)

// AppInformationReader is a Reader for the AppInformation structure.
type AppInformationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AppInformationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewAppInformationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewAppInformationBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/v1/info] AppInformation", response, response.Code())
	}
}

// NewAppInformationOK creates a AppInformationOK with default headers values
func NewAppInformationOK() *AppInformationOK {
	return &AppInformationOK{}
}

/*
AppInformationOK describes a response with status code 200, with default header values.

Application information
*/
type AppInformationOK struct {
	Payload *models.AppInformation
}

// IsSuccess returns true when this app information o k response has a 2xx status code
func (o *AppInformationOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this app information o k response has a 3xx status code
func (o *AppInformationOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this app information o k response has a 4xx status code
func (o *AppInformationOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this app information o k response has a 5xx status code
func (o *AppInformationOK) IsServerError() bool {
	return false
}

// IsCode returns true when this app information o k response a status code equal to that given
func (o *AppInformationOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the app information o k response
func (o *AppInformationOK) Code() int {
	return 200
}

func (o *AppInformationOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/info][%d] appInformationOK %s", 200, payload)
}

func (o *AppInformationOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/info][%d] appInformationOK %s", 200, payload)
}

func (o *AppInformationOK) GetPayload() *models.AppInformation {
	return o.Payload
}

func (o *AppInformationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AppInformation)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewAppInformationBadRequest creates a AppInformationBadRequest with default headers values
func NewAppInformationBadRequest() *AppInformationBadRequest {
	return &AppInformationBadRequest{}
}

/*
	AppInformationBadRequest describes a response with status code 400, with default header values.

	Server error will return with a 400 status code

with the error message in the body
*/
type AppInformationBadRequest struct {
	Payload string
}

// IsSuccess returns true when this app information bad request response has a 2xx status code
func (o *AppInformationBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this app information bad request response has a 3xx status code
func (o *AppInformationBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this app information bad request response has a 4xx status code
func (o *AppInformationBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this app information bad request response has a 5xx status code
func (o *AppInformationBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this app information bad request response a status code equal to that given
func (o *AppInformationBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the app information bad request response
func (o *AppInformationBadRequest) Code() int {
	return 400
}

func (o *AppInformationBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/info][%d] appInformationBadRequest %s", 400, payload)
}

func (o *AppInformationBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/info][%d] appInformationBadRequest %s", 400, payload)
}

func (o *AppInformationBadRequest) GetPayload() string {
	return o.Payload
}

func (o *AppInformationBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
