// Code generated by go-swagger; DO NOT EDIT.

package application

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// WebUIConfigurationResponseReader is a Reader for the WebUIConfigurationResponse structure.
type WebUIConfigurationResponseReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *WebUIConfigurationResponseReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewWebUIConfigurationResponseOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewWebUIConfigurationResponseBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/v1/webui] WebUIConfigurationResponse", response, response.Code())
	}
}

// NewWebUIConfigurationResponseOK creates a WebUIConfigurationResponseOK with default headers values
func NewWebUIConfigurationResponseOK() *WebUIConfigurationResponseOK {
	return &WebUIConfigurationResponseOK{}
}

/*
WebUIConfigurationResponseOK describes a response with status code 200, with default header values.

Web UI configuration response
*/
type WebUIConfigurationResponseOK struct {
	Payload *WebUIConfigurationResponseOKBody
}

// IsSuccess returns true when this web Ui configuration response o k response has a 2xx status code
func (o *WebUIConfigurationResponseOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this web Ui configuration response o k response has a 3xx status code
func (o *WebUIConfigurationResponseOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this web Ui configuration response o k response has a 4xx status code
func (o *WebUIConfigurationResponseOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this web Ui configuration response o k response has a 5xx status code
func (o *WebUIConfigurationResponseOK) IsServerError() bool {
	return false
}

// IsCode returns true when this web Ui configuration response o k response a status code equal to that given
func (o *WebUIConfigurationResponseOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the web Ui configuration response o k response
func (o *WebUIConfigurationResponseOK) Code() int {
	return 200
}

func (o *WebUIConfigurationResponseOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/webui][%d] webUiConfigurationResponseOK %s", 200, payload)
}

func (o *WebUIConfigurationResponseOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/webui][%d] webUiConfigurationResponseOK %s", 200, payload)
}

func (o *WebUIConfigurationResponseOK) GetPayload() *WebUIConfigurationResponseOKBody {
	return o.Payload
}

func (o *WebUIConfigurationResponseOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(WebUIConfigurationResponseOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewWebUIConfigurationResponseBadRequest creates a WebUIConfigurationResponseBadRequest with default headers values
func NewWebUIConfigurationResponseBadRequest() *WebUIConfigurationResponseBadRequest {
	return &WebUIConfigurationResponseBadRequest{}
}

/*
	WebUIConfigurationResponseBadRequest describes a response with status code 400, with default header values.

	Server error will return with a 400 status code

with the error message in the body
*/
type WebUIConfigurationResponseBadRequest struct {
	Payload string
}

// IsSuccess returns true when this web Ui configuration response bad request response has a 2xx status code
func (o *WebUIConfigurationResponseBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this web Ui configuration response bad request response has a 3xx status code
func (o *WebUIConfigurationResponseBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this web Ui configuration response bad request response has a 4xx status code
func (o *WebUIConfigurationResponseBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this web Ui configuration response bad request response has a 5xx status code
func (o *WebUIConfigurationResponseBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this web Ui configuration response bad request response a status code equal to that given
func (o *WebUIConfigurationResponseBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the web Ui configuration response bad request response
func (o *WebUIConfigurationResponseBadRequest) Code() int {
	return 400
}

func (o *WebUIConfigurationResponseBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/webui][%d] webUiConfigurationResponseBadRequest %s", 400, payload)
}

func (o *WebUIConfigurationResponseBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/webui][%d] webUiConfigurationResponseBadRequest %s", 400, payload)
}

func (o *WebUIConfigurationResponseBadRequest) GetPayload() string {
	return o.Payload
}

func (o *WebUIConfigurationResponseBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

/*
WebUIConfigurationResponseOKBody web UI configuration response o k body
swagger:model WebUIConfigurationResponseOKBody
*/
type WebUIConfigurationResponseOKBody struct {

	// Whether Chaos support is enabled at runtime
	ChaosEnabled bool `json:"ChaosEnabled,omitempty"`

	// Whether messages with duplicate IDs are ignored
	DuplicatesIgnored bool `json:"DuplicatesIgnored,omitempty"`

	// Whether the delete button should be hidden
	HideDeleteAllButton bool `json:"HideDeleteAllButton,omitempty"`

	// Optional label to identify this Mailpit instance
	Label string `json:"Label,omitempty"`

	// message relay
	MessageRelay *WebUIConfigurationResponseOKBodyMessageRelay `json:"MessageRelay,omitempty"`

	// Whether SpamAssassin is enabled
	SpamAssassin bool `json:"SpamAssassin,omitempty"`
}

// Validate validates this web UI configuration response o k body
func (o *WebUIConfigurationResponseOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateMessageRelay(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *WebUIConfigurationResponseOKBody) validateMessageRelay(formats strfmt.Registry) error {
	if swag.IsZero(o.MessageRelay) { // not required
		return nil
	}

	if o.MessageRelay != nil {
		if err := o.MessageRelay.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("webUiConfigurationResponseOK" + "." + "MessageRelay")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("webUiConfigurationResponseOK" + "." + "MessageRelay")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this web UI configuration response o k body based on the context it is used
func (o *WebUIConfigurationResponseOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateMessageRelay(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *WebUIConfigurationResponseOKBody) contextValidateMessageRelay(ctx context.Context, formats strfmt.Registry) error {

	if o.MessageRelay != nil {

		if swag.IsZero(o.MessageRelay) { // not required
			return nil
		}

		if err := o.MessageRelay.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("webUiConfigurationResponseOK" + "." + "MessageRelay")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("webUiConfigurationResponseOK" + "." + "MessageRelay")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *WebUIConfigurationResponseOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *WebUIConfigurationResponseOKBody) UnmarshalBinary(b []byte) error {
	var res WebUIConfigurationResponseOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
WebUIConfigurationResponseOKBodyMessageRelay Message Relay information
swagger:model WebUIConfigurationResponseOKBodyMessageRelay
*/
type WebUIConfigurationResponseOKBodyMessageRelay struct {

	// Only allow relaying to these recipients (regex)
	AllowedRecipients string `json:"AllowedRecipients,omitempty"`

	// Block relaying to these recipients (regex)
	BlockedRecipients string `json:"BlockedRecipients,omitempty"`

	// Whether message relaying (release) is enabled
	Enabled bool `json:"Enabled,omitempty"`

	// Overrides the "From" address for all relayed messages
	OverrideFrom string `json:"OverrideFrom,omitempty"`

	// Preserve the original Message-IDs when relaying messages
	PreserveMessageIDs bool `json:"PreserveMessageIDs,omitempty"`

	// Enforced Return-Path (if set) for relay bounces
	ReturnPath string `json:"ReturnPath,omitempty"`

	// The configured SMTP server address
	SMTPServer string `json:"SMTPServer,omitempty"`
}

// Validate validates this web UI configuration response o k body message relay
func (o *WebUIConfigurationResponseOKBodyMessageRelay) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this web UI configuration response o k body message relay based on context it is used
func (o *WebUIConfigurationResponseOKBodyMessageRelay) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *WebUIConfigurationResponseOKBodyMessageRelay) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *WebUIConfigurationResponseOKBodyMessageRelay) UnmarshalBinary(b []byte) error {
	var res WebUIConfigurationResponseOKBodyMessageRelay
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
