// Code generated by go-swagger; DO NOT EDIT.

package application

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewWebUIConfigurationResponseParams creates a new WebUIConfigurationResponseParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewWebUIConfigurationResponseParams() *WebUIConfigurationResponseParams {
	return &WebUIConfigurationResponseParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewWebUIConfigurationResponseParamsWithTimeout creates a new WebUIConfigurationResponseParams object
// with the ability to set a timeout on a request.
func NewWebUIConfigurationResponseParamsWithTimeout(timeout time.Duration) *WebUIConfigurationResponseParams {
	return &WebUIConfigurationResponseParams{
		timeout: timeout,
	}
}

// NewWebUIConfigurationResponseParamsWithContext creates a new WebUIConfigurationResponseParams object
// with the ability to set a context for a request.
func NewWebUIConfigurationResponseParamsWithContext(ctx context.Context) *WebUIConfigurationResponseParams {
	return &WebUIConfigurationResponseParams{
		Context: ctx,
	}
}

// NewWebUIConfigurationResponseParamsWithHTTPClient creates a new WebUIConfigurationResponseParams object
// with the ability to set a custom HTTPClient for a request.
func NewWebUIConfigurationResponseParamsWithHTTPClient(client *http.Client) *WebUIConfigurationResponseParams {
	return &WebUIConfigurationResponseParams{
		HTTPClient: client,
	}
}

/*
WebUIConfigurationResponseParams contains all the parameters to send to the API endpoint

	for the web UI configuration response operation.

	Typically these are written to a http.Request.
*/
type WebUIConfigurationResponseParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the web UI configuration response params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *WebUIConfigurationResponseParams) WithDefaults() *WebUIConfigurationResponseParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the web UI configuration response params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *WebUIConfigurationResponseParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the web UI configuration response params
func (o *WebUIConfigurationResponseParams) WithTimeout(timeout time.Duration) *WebUIConfigurationResponseParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the web UI configuration response params
func (o *WebUIConfigurationResponseParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the web UI configuration response params
func (o *WebUIConfigurationResponseParams) WithContext(ctx context.Context) *WebUIConfigurationResponseParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the web UI configuration response params
func (o *WebUIConfigurationResponseParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the web UI configuration response params
func (o *WebUIConfigurationResponseParams) WithHTTPClient(client *http.Client) *WebUIConfigurationResponseParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the web UI configuration response params
func (o *WebUIConfigurationResponseParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *WebUIConfigurationResponseParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
